[project]
name = "landan-desktop-dearpygui"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "click>=8.1.0",
    "dearpygui>=2.3.1",
    "grpcio>=1.80.0",
    "protobuf>=6.0.0",
    "python-dotenv>=1.0.0",
    "pyyaml>=6.0",
    "pyobjc-framework-avfoundation>=12.2.2 ; sys_platform == 'darwin'",
    "pyobjc-framework-cocoa>=12.2.2 ; sys_platform == 'darwin'",
    "pyobjc-framework-quartz>=12.2.2 ; sys_platform == 'darwin'",
    "dependency-injector>=4.49.1",
]
