# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.recognition.ir.inference.game import sicbo_pb2 as recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2


class SicboServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeItems = channel.unary_unary(
                '/pb.recognition.ir.inference.game.SicboService/RecognizeItems',
                request_serializer=recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeItemsRequest.SerializeToString,
                response_deserializer=recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeItemsResponse.FromString,
                _registered_method=True)
        self.RecognizeObjects = channel.unary_stream(
                '/pb.recognition.ir.inference.game.SicboService/RecognizeObjects',
                request_serializer=recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeObjectsRequest.SerializeToString,
                response_deserializer=recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeObjectsResponse.FromString,
                _registered_method=True)
        self.RecognizeAll = channel.unary_unary(
                '/pb.recognition.ir.inference.game.SicboService/RecognizeAll',
                request_serializer=recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeAllRequest.SerializeToString,
                response_deserializer=recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeAllResponse.FromString,
                _registered_method=True)


class SicboServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RecognizeItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SicboServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeItems': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeItems,
                    request_deserializer=recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeItemsRequest.FromString,
                    response_serializer=recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeItemsResponse.SerializeToString,
            ),
            'RecognizeObjects': grpc.unary_stream_rpc_method_handler(
                    servicer.RecognizeObjects,
                    request_deserializer=recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeObjectsRequest.FromString,
                    response_serializer=recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeObjectsResponse.SerializeToString,
            ),
            'RecognizeAll': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeAll,
                    request_deserializer=recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeAllRequest.FromString,
                    response_serializer=recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeAllResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.recognition.ir.inference.game.SicboService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.recognition.ir.inference.game.SicboService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SicboService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizeItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.recognition.ir.inference.game.SicboService/RecognizeItems',
            recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeItemsRequest.SerializeToString,
            recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pb.recognition.ir.inference.game.SicboService/RecognizeObjects',
            recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeObjectsRequest.SerializeToString,
            recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.recognition.ir.inference.game.SicboService/RecognizeAll',
            recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeAllRequest.SerializeToString,
            recognition_dot_ir_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
