# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.facade.admin.resource import game_pb2 as facade_dot_admin_dot_resource_dot_game__pb2


class GameControllerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddOne = channel.unary_unary(
                '/pb.facade.admin.resource.GameController/AddOne',
                request_serializer=facade_dot_admin_dot_resource_dot_game__pb2.GameAddOneRequest.SerializeToString,
                response_deserializer=facade_dot_admin_dot_resource_dot_game__pb2.GameAddOneResponse.FromString,
                _registered_method=True)
        self.EditOne = channel.unary_unary(
                '/pb.facade.admin.resource.GameController/EditOne',
                request_serializer=facade_dot_admin_dot_resource_dot_game__pb2.GameEditOneRequest.SerializeToString,
                response_deserializer=facade_dot_admin_dot_resource_dot_game__pb2.GameEditOneResponse.FromString,
                _registered_method=True)
        self.RemoveOne = channel.unary_unary(
                '/pb.facade.admin.resource.GameController/RemoveOne',
                request_serializer=facade_dot_admin_dot_resource_dot_game__pb2.GameRemoveOneRequest.SerializeToString,
                response_deserializer=facade_dot_admin_dot_resource_dot_game__pb2.GameRemoveOneResponse.FromString,
                _registered_method=True)
        self.ShowOne = channel.unary_unary(
                '/pb.facade.admin.resource.GameController/ShowOne',
                request_serializer=facade_dot_admin_dot_resource_dot_game__pb2.GameShowOneRequest.SerializeToString,
                response_deserializer=facade_dot_admin_dot_resource_dot_game__pb2.GameShowOneResponse.FromString,
                _registered_method=True)
        self.ShowOnes = channel.unary_unary(
                '/pb.facade.admin.resource.GameController/ShowOnes',
                request_serializer=facade_dot_admin_dot_resource_dot_game__pb2.GameShowOnesRequest.SerializeToString,
                response_deserializer=facade_dot_admin_dot_resource_dot_game__pb2.GameShowOnesResponse.FromString,
                _registered_method=True)


class GameControllerServicer:
    """Missing associated documentation comment in .proto file."""

    def AddOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOnes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddOne': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOne,
                    request_deserializer=facade_dot_admin_dot_resource_dot_game__pb2.GameAddOneRequest.FromString,
                    response_serializer=facade_dot_admin_dot_resource_dot_game__pb2.GameAddOneResponse.SerializeToString,
            ),
            'EditOne': grpc.unary_unary_rpc_method_handler(
                    servicer.EditOne,
                    request_deserializer=facade_dot_admin_dot_resource_dot_game__pb2.GameEditOneRequest.FromString,
                    response_serializer=facade_dot_admin_dot_resource_dot_game__pb2.GameEditOneResponse.SerializeToString,
            ),
            'RemoveOne': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveOne,
                    request_deserializer=facade_dot_admin_dot_resource_dot_game__pb2.GameRemoveOneRequest.FromString,
                    response_serializer=facade_dot_admin_dot_resource_dot_game__pb2.GameRemoveOneResponse.SerializeToString,
            ),
            'ShowOne': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOne,
                    request_deserializer=facade_dot_admin_dot_resource_dot_game__pb2.GameShowOneRequest.FromString,
                    response_serializer=facade_dot_admin_dot_resource_dot_game__pb2.GameShowOneResponse.SerializeToString,
            ),
            'ShowOnes': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOnes,
                    request_deserializer=facade_dot_admin_dot_resource_dot_game__pb2.GameShowOnesRequest.FromString,
                    response_serializer=facade_dot_admin_dot_resource_dot_game__pb2.GameShowOnesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.facade.admin.resource.GameController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.facade.admin.resource.GameController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameController:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.facade.admin.resource.GameController/AddOne',
            facade_dot_admin_dot_resource_dot_game__pb2.GameAddOneRequest.SerializeToString,
            facade_dot_admin_dot_resource_dot_game__pb2.GameAddOneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.facade.admin.resource.GameController/EditOne',
            facade_dot_admin_dot_resource_dot_game__pb2.GameEditOneRequest.SerializeToString,
            facade_dot_admin_dot_resource_dot_game__pb2.GameEditOneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.facade.admin.resource.GameController/RemoveOne',
            facade_dot_admin_dot_resource_dot_game__pb2.GameRemoveOneRequest.SerializeToString,
            facade_dot_admin_dot_resource_dot_game__pb2.GameRemoveOneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.facade.admin.resource.GameController/ShowOne',
            facade_dot_admin_dot_resource_dot_game__pb2.GameShowOneRequest.SerializeToString,
            facade_dot_admin_dot_resource_dot_game__pb2.GameShowOneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOnes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.facade.admin.resource.GameController/ShowOnes',
            facade_dot_admin_dot_resource_dot_game__pb2.GameShowOnesRequest.SerializeToString,
            facade_dot_admin_dot_resource_dot_game__pb2.GameShowOnesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
