# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: facade/register/authenticator.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'facade/register/authenticator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#facade/register/authenticator.proto\x12\x12pb.facade.register\x1a\x0c\x63ommon.proto\"O\n\x1a\x41uthenticatorSignInRequest\x12\x31\n\x08variable\x18\x01 \x01(\x0b\x32\x15.pb.StaffUserVariableR\x08variable\"C\n\x1b\x41uthenticatorSignInResponse\x12$\n\rauthorization\x18\x01 \x01(\tR\rauthorization2\x84\x01\n\x17\x41uthenticatorController\x12i\n\x06SignIn\x12..pb.facade.register.AuthenticatorSignInRequest\x1a/.pb.facade.register.AuthenticatorSignInResponseB\xd4\x01\n\x16\x63om.pb.facade.registerB\x12\x41uthenticatorProtoP\x01Z<github.com/wegdevio/pk-studio-reader/pkg/api/facade/register\xa2\x02\x03PFR\xaa\x02\x12Pb.Facade.Register\xca\x02\x12Pb\\Facade\\Register\xe2\x02\x1ePb\\Facade\\Register\\GPBMetadata\xea\x02\x14Pb::Facade::Registerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'facade.register.authenticator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.pb.facade.registerB\022AuthenticatorProtoP\001Z<github.com/wegdevio/pk-studio-reader/pkg/api/facade/register\242\002\003PFR\252\002\022Pb.Facade.Register\312\002\022Pb\\Facade\\Register\342\002\036Pb\\Facade\\Register\\GPBMetadata\352\002\024Pb::Facade::Register'
  _globals['_AUTHENTICATORSIGNINREQUEST']._serialized_start=73
  _globals['_AUTHENTICATORSIGNINREQUEST']._serialized_end=152
  _globals['_AUTHENTICATORSIGNINRESPONSE']._serialized_start=154
  _globals['_AUTHENTICATORSIGNINRESPONSE']._serialized_end=221
  _globals['_AUTHENTICATORCONTROLLER']._serialized_start=224
  _globals['_AUTHENTICATORCONTROLLER']._serialized_end=356
# @@protoc_insertion_point(module_scope)
