# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recognition/ir.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'recognition/ir.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recognition/ir.proto\x12\x0epb.recognition\"\x99\x01\n\x05Poker\x12\x12\n\x04rank\x18\x01 \x01(\tR\x04rank\x12\x12\n\x04suit\x18\x02 \x01(\tR\x04suit\x12\x0c\n\x01x\x18\x03 \x01(\x05R\x01x\x12\x0c\n\x01y\x18\x04 \x01(\x05R\x01y\x12\x14\n\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x06 \x01(\x05R\x06height\x12\x1e\n\nconfidence\x18\x07 \x01(\x02R\nconfidence\"p\n\x04\x44isk\x12\x0c\n\x01x\x18\x01 \x01(\x05R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x04 \x01(\x05R\x06height\x12\x1e\n\nconfidence\x18\x05 \x01(\x02R\nconfidence\"\x85\x01\n\x03\x44ie\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\x12\x0c\n\x01x\x18\x02 \x01(\x05R\x01x\x12\x0c\n\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x05 \x01(\x05R\x06height\x12\x1e\n\nconfidence\x18\x06 \x01(\x02R\nconfidence\"\x88\x01\n\x06Object\x12\x14\n\x05\x63lass\x18\x01 \x01(\tR\x05\x63lass\x12\x0c\n\x01x\x18\x02 \x01(\x05R\x01x\x12\x0c\n\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x05 \x01(\x05R\x06height\x12\x1e\n\nconfidence\x18\x06 \x01(\x02R\nconfidenceB\xb0\x01\n\x12\x63om.pb.recognitionB\x07IrProtoP\x01Z8github.com/wegdevio/pk-studio-reader/pkg/api/recognition\xa2\x02\x03PRX\xaa\x02\x0ePb.Recognition\xca\x02\x0ePb\\Recognition\xe2\x02\x1aPb\\Recognition\\GPBMetadata\xea\x02\x0fPb::Recognitionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recognition.ir_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.pb.recognitionB\007IrProtoP\001Z8github.com/wegdevio/pk-studio-reader/pkg/api/recognition\242\002\003PRX\252\002\016Pb.Recognition\312\002\016Pb\\Recognition\342\002\032Pb\\Recognition\\GPBMetadata\352\002\017Pb::Recognition'
  _globals['_POKER']._serialized_start=41
  _globals['_POKER']._serialized_end=194
  _globals['_DISK']._serialized_start=196
  _globals['_DISK']._serialized_end=308
  _globals['_DIE']._serialized_start=311
  _globals['_DIE']._serialized_end=444
  _globals['_OBJECT']._serialized_start=447
  _globals['_OBJECT']._serialized_end=583
# @@protoc_insertion_point(module_scope)
