# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ir/table/inference/die.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'ir/table/inference/die.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cir/table/inference/die.proto\x12\x15pb.ir.table.inference\"\x18\n\x16\x44ieRecognizeDieRequest\"\x1a\n\x18\x44ieRecognizeSceneRequest\"\x18\n\x16\x44ieRecognizeAllRequest\"I\n\x17\x44ieRecognizeDieResponse\x12.\n\x04\x64ice\x18\x01 \x03(\x0b\x32\x1a.pb.ir.table.inference.DieR\x04\x64ice\"T\n\x19\x44ieRecognizeSceneResponse\x12\x37\n\x06scenes\x18\x01 \x03(\x0b\x32\x1f.pb.ir.table.inference.DieSceneR\x06scenes\"\x82\x01\n\x17\x44ieRecognizeAllResponse\x12\x37\n\x06scenes\x18\x01 \x03(\x0b\x32\x1f.pb.ir.table.inference.DieSceneR\x06scenes\x12.\n\x04\x64ice\x18\x02 \x03(\x0b\x32\x1a.pb.ir.table.inference.DieR\x04\x64ice\"o\n\x03\x44ie\x12\x0c\n\x01x\x18\x01 \x01(\x05R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x04 \x01(\x05R\x06height\x12\x1e\n\nconfidence\x18\x05 \x01(\x02R\nconfidence\"t\n\x08\x44ieScene\x12\x0c\n\x01x\x18\x01 \x01(\x05R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x04 \x01(\x05R\x06height\x12\x1e\n\nconfidence\x18\x05 \x01(\x02R\nconfidence2\xdf\x02\n\nDieService\x12m\n\x0cRecognizeDie\x12-.pb.ir.table.inference.DieRecognizeDieRequest\x1a..pb.ir.table.inference.DieRecognizeDieResponse\x12s\n\x0eRecognizeScene\x12/.pb.ir.table.inference.DieRecognizeSceneRequest\x1a\x30.pb.ir.table.inference.DieRecognizeSceneResponse\x12m\n\x0cRecognizeAll\x12-.pb.ir.table.inference.DieRecognizeAllRequest\x1a..pb.ir.table.inference.DieRecognizeAllResponseB\xde\x01\n\x19\x63om.pb.ir.table.inferenceB\x08\x44ieProtoP\x01Z?github.com/wegdevio/pk-studio-reader/pkg/api/ir/table/inference\xa2\x02\x04PITI\xaa\x02\x15Pb.Ir.Table.Inference\xca\x02\x15Pb\\Ir\\Table\\Inference\xe2\x02!Pb\\Ir\\Table\\Inference\\GPBMetadata\xea\x02\x18Pb::Ir::Table::Inferenceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ir.table.inference.die_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.pb.ir.table.inferenceB\010DieProtoP\001Z?github.com/wegdevio/pk-studio-reader/pkg/api/ir/table/inference\242\002\004PITI\252\002\025Pb.Ir.Table.Inference\312\002\025Pb\\Ir\\Table\\Inference\342\002!Pb\\Ir\\Table\\Inference\\GPBMetadata\352\002\030Pb::Ir::Table::Inference'
  _globals['_DIERECOGNIZEDIEREQUEST']._serialized_start=55
  _globals['_DIERECOGNIZEDIEREQUEST']._serialized_end=79
  _globals['_DIERECOGNIZESCENEREQUEST']._serialized_start=81
  _globals['_DIERECOGNIZESCENEREQUEST']._serialized_end=107
  _globals['_DIERECOGNIZEALLREQUEST']._serialized_start=109
  _globals['_DIERECOGNIZEALLREQUEST']._serialized_end=133
  _globals['_DIERECOGNIZEDIERESPONSE']._serialized_start=135
  _globals['_DIERECOGNIZEDIERESPONSE']._serialized_end=208
  _globals['_DIERECOGNIZESCENERESPONSE']._serialized_start=210
  _globals['_DIERECOGNIZESCENERESPONSE']._serialized_end=294
  _globals['_DIERECOGNIZEALLRESPONSE']._serialized_start=297
  _globals['_DIERECOGNIZEALLRESPONSE']._serialized_end=427
  _globals['_DIE']._serialized_start=429
  _globals['_DIE']._serialized_end=540
  _globals['_DIESCENE']._serialized_start=542
  _globals['_DIESCENE']._serialized_end=658
  _globals['_DIESERVICE']._serialized_start=661
  _globals['_DIESERVICE']._serialized_end=1012
# @@protoc_insertion_point(module_scope)
