# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.ir.table.inference import die_pb2 as ir_dot_table_dot_inference_dot_die__pb2


class DieServiceStub:
    """
    提供三種 api
    1. 辨識 骰子 的 位置
    2. 辨識 場景 的 位置
    3. 辨識 骰子 + 場景  位置
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeDie = channel.unary_unary(
                '/pb.ir.table.inference.DieService/RecognizeDie',
                request_serializer=ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeDieRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeDieResponse.FromString,
                _registered_method=True)
        self.RecognizeScene = channel.unary_unary(
                '/pb.ir.table.inference.DieService/RecognizeScene',
                request_serializer=ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeSceneRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeSceneResponse.FromString,
                _registered_method=True)
        self.RecognizeAll = channel.unary_unary(
                '/pb.ir.table.inference.DieService/RecognizeAll',
                request_serializer=ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeAllRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeAllResponse.FromString,
                _registered_method=True)


class DieServiceServicer:
    """
    提供三種 api
    1. 辨識 骰子 的 位置
    2. 辨識 場景 的 位置
    3. 辨識 骰子 + 場景  位置
    """

    def RecognizeDie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeDie': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeDie,
                    request_deserializer=ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeDieRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeDieResponse.SerializeToString,
            ),
            'RecognizeScene': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeScene,
                    request_deserializer=ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeSceneRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeSceneResponse.SerializeToString,
            ),
            'RecognizeAll': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeAll,
                    request_deserializer=ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeAllRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeAllResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ir.table.inference.DieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.ir.table.inference.DieService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DieService:
    """
    提供三種 api
    1. 辨識 骰子 的 位置
    2. 辨識 場景 的 位置
    3. 辨識 骰子 + 場景  位置
    """

    @staticmethod
    def RecognizeDie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.DieService/RecognizeDie',
            ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeDieRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeDieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.DieService/RecognizeScene',
            ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeSceneRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.DieService/RecognizeAll',
            ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeAllRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_die__pb2.DieRecognizeAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
