# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ir/table/inference/disk.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'ir/table/inference/disk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dir/table/inference/disk.proto\x12\x15pb.ir.table.inference\"\x1a\n\x18\x44iskRecognizeDiskRequest\"\x1b\n\x19\x44iskRecognizeSceneRequest\"\x19\n\x17\x44iskRecognizeAllRequest\"N\n\x19\x44iskRecognizeDiskResponse\x12\x31\n\x05\x64isks\x18\x01 \x03(\x0b\x32\x1b.pb.ir.table.inference.DiskR\x05\x64isks\"V\n\x1a\x44iskRecognizeSceneResponse\x12\x38\n\x06scenes\x18\x01 \x03(\x0b\x32 .pb.ir.table.inference.DiskSceneR\x06scenes\"\x87\x01\n\x18\x44iskRecognizeAllResponse\x12\x38\n\x06scenes\x18\x01 \x03(\x0b\x32 .pb.ir.table.inference.DiskSceneR\x06scenes\x12\x31\n\x05\x64isks\x18\x02 \x03(\x0b\x32\x1b.pb.ir.table.inference.DiskR\x05\x64isks\"p\n\x04\x44isk\x12\x0c\n\x01x\x18\x01 \x01(\x05R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x04 \x01(\x05R\x06height\x12\x1e\n\nconfidence\x18\x05 \x01(\x02R\nconfidence\"u\n\tDiskScene\x12\x0c\n\x01x\x18\x01 \x01(\x05R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x04 \x01(\x05R\x06height\x12\x1e\n\nconfidence\x18\x05 \x01(\x02R\nconfidence2\xe9\x02\n\x0b\x44iskService\x12r\n\rRecognizeDisk\x12/.pb.ir.table.inference.DiskRecognizeDiskRequest\x1a\x30.pb.ir.table.inference.DiskRecognizeDiskResponse\x12u\n\x0eRecognizeScene\x12\x30.pb.ir.table.inference.DiskRecognizeSceneRequest\x1a\x31.pb.ir.table.inference.DiskRecognizeSceneResponse\x12o\n\x0cRecognizeAll\x12..pb.ir.table.inference.DiskRecognizeAllRequest\x1a/.pb.ir.table.inference.DiskRecognizeAllResponseB\xdf\x01\n\x19\x63om.pb.ir.table.inferenceB\tDiskProtoP\x01Z?github.com/wegdevio/pk-studio-reader/pkg/api/ir/table/inference\xa2\x02\x04PITI\xaa\x02\x15Pb.Ir.Table.Inference\xca\x02\x15Pb\\Ir\\Table\\Inference\xe2\x02!Pb\\Ir\\Table\\Inference\\GPBMetadata\xea\x02\x18Pb::Ir::Table::Inferenceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ir.table.inference.disk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.pb.ir.table.inferenceB\tDiskProtoP\001Z?github.com/wegdevio/pk-studio-reader/pkg/api/ir/table/inference\242\002\004PITI\252\002\025Pb.Ir.Table.Inference\312\002\025Pb\\Ir\\Table\\Inference\342\002!Pb\\Ir\\Table\\Inference\\GPBMetadata\352\002\030Pb::Ir::Table::Inference'
  _globals['_DISKRECOGNIZEDISKREQUEST']._serialized_start=56
  _globals['_DISKRECOGNIZEDISKREQUEST']._serialized_end=82
  _globals['_DISKRECOGNIZESCENEREQUEST']._serialized_start=84
  _globals['_DISKRECOGNIZESCENEREQUEST']._serialized_end=111
  _globals['_DISKRECOGNIZEALLREQUEST']._serialized_start=113
  _globals['_DISKRECOGNIZEALLREQUEST']._serialized_end=138
  _globals['_DISKRECOGNIZEDISKRESPONSE']._serialized_start=140
  _globals['_DISKRECOGNIZEDISKRESPONSE']._serialized_end=218
  _globals['_DISKRECOGNIZESCENERESPONSE']._serialized_start=220
  _globals['_DISKRECOGNIZESCENERESPONSE']._serialized_end=306
  _globals['_DISKRECOGNIZEALLRESPONSE']._serialized_start=309
  _globals['_DISKRECOGNIZEALLRESPONSE']._serialized_end=444
  _globals['_DISK']._serialized_start=446
  _globals['_DISK']._serialized_end=558
  _globals['_DISKSCENE']._serialized_start=560
  _globals['_DISKSCENE']._serialized_end=677
  _globals['_DISKSERVICE']._serialized_start=680
  _globals['_DISKSERVICE']._serialized_end=1041
# @@protoc_insertion_point(module_scope)
