# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.ir.table.inference import disk_pb2 as ir_dot_table_dot_inference_dot_disk__pb2


class DiskServiceStub:
    """
    提供三種 api
    1. 辨識 圓盤 的 位置
    2. 辨識 場景 的 位置
    3. 辨識 圓盤 + 場景  位置
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeDisk = channel.unary_unary(
                '/pb.ir.table.inference.DiskService/RecognizeDisk',
                request_serializer=ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeDiskRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeDiskResponse.FromString,
                _registered_method=True)
        self.RecognizeScene = channel.unary_unary(
                '/pb.ir.table.inference.DiskService/RecognizeScene',
                request_serializer=ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeSceneRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeSceneResponse.FromString,
                _registered_method=True)
        self.RecognizeAll = channel.unary_unary(
                '/pb.ir.table.inference.DiskService/RecognizeAll',
                request_serializer=ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeAllRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeAllResponse.FromString,
                _registered_method=True)


class DiskServiceServicer:
    """
    提供三種 api
    1. 辨識 圓盤 的 位置
    2. 辨識 場景 的 位置
    3. 辨識 圓盤 + 場景  位置
    """

    def RecognizeDisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeDisk': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeDisk,
                    request_deserializer=ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeDiskRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeDiskResponse.SerializeToString,
            ),
            'RecognizeScene': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeScene,
                    request_deserializer=ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeSceneRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeSceneResponse.SerializeToString,
            ),
            'RecognizeAll': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeAll,
                    request_deserializer=ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeAllRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeAllResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ir.table.inference.DiskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.ir.table.inference.DiskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiskService:
    """
    提供三種 api
    1. 辨識 圓盤 的 位置
    2. 辨識 場景 的 位置
    3. 辨識 圓盤 + 場景  位置
    """

    @staticmethod
    def RecognizeDisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.DiskService/RecognizeDisk',
            ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeDiskRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeDiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.DiskService/RecognizeScene',
            ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeSceneRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.DiskService/RecognizeAll',
            ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeAllRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_disk__pb2.DiskRecognizeAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
