# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.ir.table.inference import poker_pb2 as ir_dot_table_dot_inference_dot_poker__pb2


class PokerServiceStub:
    """
    提供三種 api
    1. 辨識 撲克牌的 位置跟種類
    2. 辨識 場景 的 位置跟種類
    3. 辨識 撲克牌 + 場景  位置跟種類
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizePoker = channel.unary_unary(
                '/pb.ir.table.inference.PokerService/RecognizePoker',
                request_serializer=ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizePokerRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizePokerResponse.FromString,
                _registered_method=True)
        self.RecognizeScene = channel.unary_unary(
                '/pb.ir.table.inference.PokerService/RecognizeScene',
                request_serializer=ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizeSceneRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizeSceneResponse.FromString,
                _registered_method=True)
        self.RecognizeAll = channel.unary_unary(
                '/pb.ir.table.inference.PokerService/RecognizeAll',
                request_serializer=ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizeAllRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizeAllResponse.FromString,
                _registered_method=True)


class PokerServiceServicer:
    """
    提供三種 api
    1. 辨識 撲克牌的 位置跟種類
    2. 辨識 場景 的 位置跟種類
    3. 辨識 撲克牌 + 場景  位置跟種類
    """

    def RecognizePoker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizePoker': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizePoker,
                    request_deserializer=ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizePokerRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizePokerResponse.SerializeToString,
            ),
            'RecognizeScene': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeScene,
                    request_deserializer=ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizeSceneRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizeSceneResponse.SerializeToString,
            ),
            'RecognizeAll': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeAll,
                    request_deserializer=ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizeAllRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizeAllResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ir.table.inference.PokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.ir.table.inference.PokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PokerService:
    """
    提供三種 api
    1. 辨識 撲克牌的 位置跟種類
    2. 辨識 場景 的 位置跟種類
    3. 辨識 撲克牌 + 場景  位置跟種類
    """

    @staticmethod
    def RecognizePoker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.PokerService/RecognizePoker',
            ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizePokerRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizePokerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.PokerService/RecognizeScene',
            ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizeSceneRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizeSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.PokerService/RecognizeAll',
            ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizeAllRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_poker__pb2.PokerRecognizeAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
