# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recognition/ir/inference/object/baccarat.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'recognition/ir/inference/object/baccarat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb.recognition import ir_pb2 as recognition_dot_ir__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.recognition/ir/inference/object/baccarat.proto\x12\"pb.recognition.ir.inference.object\x1a\x14recognition/ir.proto\"!\n\x1f\x42\x61\x63\x63\x61ratRecognizeObjectsRequest\"T\n BaccaratRecognizeObjectsResponse\x12\x30\n\x07objects\x18\x01 \x03(\x0b\x32\x16.pb.recognition.ObjectR\x07objects2\xb1\x01\n\x0f\x42\x61\x63\x63\x61ratService\x12\x9d\x01\n\x10RecognizeObjects\x12\x43.pb.recognition.ir.inference.object.BaccaratRecognizeObjectsRequest\x1a\x44.pb.recognition.ir.inference.object.BaccaratRecognizeObjectsResponseB\xb3\x02\n&com.pb.recognition.ir.inference.objectB\rBaccaratProtoP\x01ZLgithub.com/wegdevio/pk-studio-reader/pkg/api/recognition/ir/inference/object\xa2\x02\x05PRIIO\xaa\x02\"Pb.Recognition.Ir.Inference.Object\xca\x02\"Pb\\Recognition\\Ir\\Inference\\Object\xe2\x02.Pb\\Recognition\\Ir\\Inference\\Object\\GPBMetadata\xea\x02&Pb::Recognition::Ir::Inference::Objectb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recognition.ir.inference.object.baccarat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.pb.recognition.ir.inference.objectB\rBaccaratProtoP\001ZLgithub.com/wegdevio/pk-studio-reader/pkg/api/recognition/ir/inference/object\242\002\005PRIIO\252\002\"Pb.Recognition.Ir.Inference.Object\312\002\"Pb\\Recognition\\Ir\\Inference\\Object\342\002.Pb\\Recognition\\Ir\\Inference\\Object\\GPBMetadata\352\002&Pb::Recognition::Ir::Inference::Object'
  _globals['_BACCARATRECOGNIZEOBJECTSREQUEST']._serialized_start=108
  _globals['_BACCARATRECOGNIZEOBJECTSREQUEST']._serialized_end=141
  _globals['_BACCARATRECOGNIZEOBJECTSRESPONSE']._serialized_start=143
  _globals['_BACCARATRECOGNIZEOBJECTSRESPONSE']._serialized_end=227
  _globals['_BACCARATSERVICE']._serialized_start=230
  _globals['_BACCARATSERVICE']._serialized_end=407
# @@protoc_insertion_point(module_scope)
