# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recognition/ir/inference/object/sicbo.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'recognition/ir/inference/object/sicbo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb.recognition import ir_pb2 as recognition_dot_ir__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+recognition/ir/inference/object/sicbo.proto\x12\"pb.recognition.ir.inference.object\x1a\x14recognition/ir.proto\"\x1e\n\x1cSicboRecognizeObjectsRequest\"Q\n\x1dSicboRecognizeObjectsResponse\x12\x30\n\x07objects\x18\x01 \x03(\x0b\x32\x16.pb.recognition.ObjectR\x07objects2\xa8\x01\n\x0cSicboService\x12\x97\x01\n\x10RecognizeObjects\x12@.pb.recognition.ir.inference.object.SicboRecognizeObjectsRequest\x1a\x41.pb.recognition.ir.inference.object.SicboRecognizeObjectsResponseB\xb0\x02\n&com.pb.recognition.ir.inference.objectB\nSicboProtoP\x01ZLgithub.com/wegdevio/pk-studio-reader/pkg/api/recognition/ir/inference/object\xa2\x02\x05PRIIO\xaa\x02\"Pb.Recognition.Ir.Inference.Object\xca\x02\"Pb\\Recognition\\Ir\\Inference\\Object\xe2\x02.Pb\\Recognition\\Ir\\Inference\\Object\\GPBMetadata\xea\x02&Pb::Recognition::Ir::Inference::Objectb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recognition.ir.inference.object.sicbo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.pb.recognition.ir.inference.objectB\nSicboProtoP\001ZLgithub.com/wegdevio/pk-studio-reader/pkg/api/recognition/ir/inference/object\242\002\005PRIIO\252\002\"Pb.Recognition.Ir.Inference.Object\312\002\"Pb\\Recognition\\Ir\\Inference\\Object\342\002.Pb\\Recognition\\Ir\\Inference\\Object\\GPBMetadata\352\002&Pb::Recognition::Ir::Inference::Object'
  _globals['_SICBORECOGNIZEOBJECTSREQUEST']._serialized_start=105
  _globals['_SICBORECOGNIZEOBJECTSREQUEST']._serialized_end=135
  _globals['_SICBORECOGNIZEOBJECTSRESPONSE']._serialized_start=137
  _globals['_SICBORECOGNIZEOBJECTSRESPONSE']._serialized_end=218
  _globals['_SICBOSERVICE']._serialized_start=221
  _globals['_SICBOSERVICE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
