# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.model import admin_permission_group_pb2 as resource_dot_model_dot_admin__permission__group__pb2


class AdminPermissionGroupModelStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddOne = channel.unary_unary(
                '/pb.resource.model.AdminPermissionGroupModel/AddOne',
                request_serializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupAddOneInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupAddOneOutput.FromString,
                _registered_method=True)
        self.ShowOnesByParentId = channel.unary_unary(
                '/pb.resource.model.AdminPermissionGroupModel/ShowOnesByParentId',
                request_serializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupShowOnesByParentIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupShowOnesByParentIdOutput.FromString,
                _registered_method=True)
        self.ShowOnesByFiltersWithSortersPagination = channel.unary_unary(
                '/pb.resource.model.AdminPermissionGroupModel/ShowOnesByFiltersWithSortersPagination',
                request_serializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupShowOnesByFiltersWithSortersPaginationInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupShowOnesByFiltersWithSortersPaginationOutput.FromString,
                _registered_method=True)
        self.EditOneById = channel.unary_unary(
                '/pb.resource.model.AdminPermissionGroupModel/EditOneById',
                request_serializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupEditOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupEditOneByIdOutput.FromString,
                _registered_method=True)
        self.RemoveOneById = channel.unary_unary(
                '/pb.resource.model.AdminPermissionGroupModel/RemoveOneById',
                request_serializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupRemoveOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupRemoveOneByIdOutput.FromString,
                _registered_method=True)
        self.TotalByFilters = channel.unary_unary(
                '/pb.resource.model.AdminPermissionGroupModel/TotalByFilters',
                request_serializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupTotalByFiltersInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupTotalByFiltersOutput.FromString,
                _registered_method=True)


class AdminPermissionGroupModelServicer:
    """Missing associated documentation comment in .proto file."""

    def AddOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOnesByParentId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOnesByFiltersWithSortersPagination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TotalByFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminPermissionGroupModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddOne': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOne,
                    request_deserializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupAddOneInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupAddOneOutput.SerializeToString,
            ),
            'ShowOnesByParentId': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOnesByParentId,
                    request_deserializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupShowOnesByParentIdInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupShowOnesByParentIdOutput.SerializeToString,
            ),
            'ShowOnesByFiltersWithSortersPagination': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOnesByFiltersWithSortersPagination,
                    request_deserializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupShowOnesByFiltersWithSortersPaginationInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupShowOnesByFiltersWithSortersPaginationOutput.SerializeToString,
            ),
            'EditOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.EditOneById,
                    request_deserializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupEditOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupEditOneByIdOutput.SerializeToString,
            ),
            'RemoveOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveOneById,
                    request_deserializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupRemoveOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupRemoveOneByIdOutput.SerializeToString,
            ),
            'TotalByFilters': grpc.unary_unary_rpc_method_handler(
                    servicer.TotalByFilters,
                    request_deserializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupTotalByFiltersInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupTotalByFiltersOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.model.AdminPermissionGroupModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.model.AdminPermissionGroupModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminPermissionGroupModel:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminPermissionGroupModel/AddOne',
            resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupAddOneInput.SerializeToString,
            resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupAddOneOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOnesByParentId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminPermissionGroupModel/ShowOnesByParentId',
            resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupShowOnesByParentIdInput.SerializeToString,
            resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupShowOnesByParentIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOnesByFiltersWithSortersPagination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminPermissionGroupModel/ShowOnesByFiltersWithSortersPagination',
            resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupShowOnesByFiltersWithSortersPaginationInput.SerializeToString,
            resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupShowOnesByFiltersWithSortersPaginationOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminPermissionGroupModel/EditOneById',
            resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupEditOneByIdInput.SerializeToString,
            resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupEditOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminPermissionGroupModel/RemoveOneById',
            resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupRemoveOneByIdInput.SerializeToString,
            resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupRemoveOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TotalByFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminPermissionGroupModel/TotalByFilters',
            resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupTotalByFiltersInput.SerializeToString,
            resource_dot_model_dot_admin__permission__group__pb2.AdminPermissionGroupTotalByFiltersOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
