# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.model import admin_permission_pb2 as resource_dot_model_dot_admin__permission__pb2


class AdminPermissionModelStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddOne = channel.unary_unary(
                '/pb.resource.model.AdminPermissionModel/AddOne',
                request_serializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionAddOneInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionAddOneOutput.FromString,
                _registered_method=True)
        self.ShowOneById = channel.unary_unary(
                '/pb.resource.model.AdminPermissionModel/ShowOneById',
                request_serializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionShowOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionShowOneByIdOutput.FromString,
                _registered_method=True)
        self.EditOneById = channel.unary_unary(
                '/pb.resource.model.AdminPermissionModel/EditOneById',
                request_serializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionEditOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionEditOneByIdOutput.FromString,
                _registered_method=True)
        self.RemoveOneById = channel.unary_unary(
                '/pb.resource.model.AdminPermissionModel/RemoveOneById',
                request_serializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionRemoveOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionRemoveOneByIdOutput.FromString,
                _registered_method=True)
        self.ShowOnesByFiltersWithSortersPagination = channel.unary_unary(
                '/pb.resource.model.AdminPermissionModel/ShowOnesByFiltersWithSortersPagination',
                request_serializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionShowOnesByFiltersWithSortersPaginationInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionShowOnesByFiltersWithSortersPaginationOutput.FromString,
                _registered_method=True)
        self.TotalByFilters = channel.unary_unary(
                '/pb.resource.model.AdminPermissionModel/TotalByFilters',
                request_serializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionTotalByFiltersInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionTotalByFiltersOutput.FromString,
                _registered_method=True)


class AdminPermissionModelServicer:
    """Missing associated documentation comment in .proto file."""

    def AddOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOnesByFiltersWithSortersPagination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TotalByFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminPermissionModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddOne': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOne,
                    request_deserializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionAddOneInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionAddOneOutput.SerializeToString,
            ),
            'ShowOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOneById,
                    request_deserializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionShowOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionShowOneByIdOutput.SerializeToString,
            ),
            'EditOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.EditOneById,
                    request_deserializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionEditOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionEditOneByIdOutput.SerializeToString,
            ),
            'RemoveOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveOneById,
                    request_deserializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionRemoveOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionRemoveOneByIdOutput.SerializeToString,
            ),
            'ShowOnesByFiltersWithSortersPagination': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOnesByFiltersWithSortersPagination,
                    request_deserializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionShowOnesByFiltersWithSortersPaginationInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionShowOnesByFiltersWithSortersPaginationOutput.SerializeToString,
            ),
            'TotalByFilters': grpc.unary_unary_rpc_method_handler(
                    servicer.TotalByFilters,
                    request_deserializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionTotalByFiltersInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__permission__pb2.AdminPermissionTotalByFiltersOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.model.AdminPermissionModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.model.AdminPermissionModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminPermissionModel:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminPermissionModel/AddOne',
            resource_dot_model_dot_admin__permission__pb2.AdminPermissionAddOneInput.SerializeToString,
            resource_dot_model_dot_admin__permission__pb2.AdminPermissionAddOneOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminPermissionModel/ShowOneById',
            resource_dot_model_dot_admin__permission__pb2.AdminPermissionShowOneByIdInput.SerializeToString,
            resource_dot_model_dot_admin__permission__pb2.AdminPermissionShowOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminPermissionModel/EditOneById',
            resource_dot_model_dot_admin__permission__pb2.AdminPermissionEditOneByIdInput.SerializeToString,
            resource_dot_model_dot_admin__permission__pb2.AdminPermissionEditOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminPermissionModel/RemoveOneById',
            resource_dot_model_dot_admin__permission__pb2.AdminPermissionRemoveOneByIdInput.SerializeToString,
            resource_dot_model_dot_admin__permission__pb2.AdminPermissionRemoveOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOnesByFiltersWithSortersPagination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminPermissionModel/ShowOnesByFiltersWithSortersPagination',
            resource_dot_model_dot_admin__permission__pb2.AdminPermissionShowOnesByFiltersWithSortersPaginationInput.SerializeToString,
            resource_dot_model_dot_admin__permission__pb2.AdminPermissionShowOnesByFiltersWithSortersPaginationOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TotalByFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminPermissionModel/TotalByFilters',
            resource_dot_model_dot_admin__permission__pb2.AdminPermissionTotalByFiltersInput.SerializeToString,
            resource_dot_model_dot_admin__permission__pb2.AdminPermissionTotalByFiltersOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
