# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.model import admin_role_pb2 as resource_dot_model_dot_admin__role__pb2


class AdminRoleModelStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddOne = channel.unary_unary(
                '/pb.resource.model.AdminRoleModel/AddOne',
                request_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleAddOneInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleAddOneOutput.FromString,
                _registered_method=True)
        self.ShowOneById = channel.unary_unary(
                '/pb.resource.model.AdminRoleModel/ShowOneById',
                request_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleShowOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleShowOneByIdOutput.FromString,
                _registered_method=True)
        self.EditOneById = channel.unary_unary(
                '/pb.resource.model.AdminRoleModel/EditOneById',
                request_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleEditOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleEditOneByIdOutput.FromString,
                _registered_method=True)
        self.RemoveOneById = channel.unary_unary(
                '/pb.resource.model.AdminRoleModel/RemoveOneById',
                request_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleRemoveOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleRemoveOneByIdOutput.FromString,
                _registered_method=True)
        self.ShowOnes = channel.unary_unary(
                '/pb.resource.model.AdminRoleModel/ShowOnes',
                request_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleShowOnesInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleShowOnesOutput.FromString,
                _registered_method=True)
        self.ShowOnesByFiltersWithSortersPagination = channel.unary_unary(
                '/pb.resource.model.AdminRoleModel/ShowOnesByFiltersWithSortersPagination',
                request_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleShowOnesByFiltersWithSortersPaginationInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleShowOnesByFiltersWithSortersPaginationOutput.FromString,
                _registered_method=True)
        self.TotalByFilters = channel.unary_unary(
                '/pb.resource.model.AdminRoleModel/TotalByFilters',
                request_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleTotalByFiltersInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleTotalByFiltersOutput.FromString,
                _registered_method=True)


class AdminRoleModelServicer:
    """Missing associated documentation comment in .proto file."""

    def AddOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOnes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOnesByFiltersWithSortersPagination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TotalByFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminRoleModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddOne': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOne,
                    request_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleAddOneInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleAddOneOutput.SerializeToString,
            ),
            'ShowOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOneById,
                    request_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleShowOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleShowOneByIdOutput.SerializeToString,
            ),
            'EditOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.EditOneById,
                    request_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleEditOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleEditOneByIdOutput.SerializeToString,
            ),
            'RemoveOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveOneById,
                    request_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleRemoveOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleRemoveOneByIdOutput.SerializeToString,
            ),
            'ShowOnes': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOnes,
                    request_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleShowOnesInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleShowOnesOutput.SerializeToString,
            ),
            'ShowOnesByFiltersWithSortersPagination': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOnesByFiltersWithSortersPagination,
                    request_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleShowOnesByFiltersWithSortersPaginationInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleShowOnesByFiltersWithSortersPaginationOutput.SerializeToString,
            ),
            'TotalByFilters': grpc.unary_unary_rpc_method_handler(
                    servicer.TotalByFilters,
                    request_deserializer=resource_dot_model_dot_admin__role__pb2.AdminRoleTotalByFiltersInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__role__pb2.AdminRoleTotalByFiltersOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.model.AdminRoleModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.model.AdminRoleModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminRoleModel:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminRoleModel/AddOne',
            resource_dot_model_dot_admin__role__pb2.AdminRoleAddOneInput.SerializeToString,
            resource_dot_model_dot_admin__role__pb2.AdminRoleAddOneOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminRoleModel/ShowOneById',
            resource_dot_model_dot_admin__role__pb2.AdminRoleShowOneByIdInput.SerializeToString,
            resource_dot_model_dot_admin__role__pb2.AdminRoleShowOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminRoleModel/EditOneById',
            resource_dot_model_dot_admin__role__pb2.AdminRoleEditOneByIdInput.SerializeToString,
            resource_dot_model_dot_admin__role__pb2.AdminRoleEditOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminRoleModel/RemoveOneById',
            resource_dot_model_dot_admin__role__pb2.AdminRoleRemoveOneByIdInput.SerializeToString,
            resource_dot_model_dot_admin__role__pb2.AdminRoleRemoveOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOnes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminRoleModel/ShowOnes',
            resource_dot_model_dot_admin__role__pb2.AdminRoleShowOnesInput.SerializeToString,
            resource_dot_model_dot_admin__role__pb2.AdminRoleShowOnesOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOnesByFiltersWithSortersPagination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminRoleModel/ShowOnesByFiltersWithSortersPagination',
            resource_dot_model_dot_admin__role__pb2.AdminRoleShowOnesByFiltersWithSortersPaginationInput.SerializeToString,
            resource_dot_model_dot_admin__role__pb2.AdminRoleShowOnesByFiltersWithSortersPaginationOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TotalByFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminRoleModel/TotalByFilters',
            resource_dot_model_dot_admin__role__pb2.AdminRoleTotalByFiltersInput.SerializeToString,
            resource_dot_model_dot_admin__role__pb2.AdminRoleTotalByFiltersOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
