# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.model import admin_user_pb2 as resource_dot_model_dot_admin__user__pb2


class AdminUserModelStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShowOneByName = channel.unary_unary(
                '/pb.resource.model.AdminUserModel/ShowOneByName',
                request_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserShowOneByNameInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserShowOneByNameOutput.FromString,
                _registered_method=True)
        self.ShowOneById = channel.unary_unary(
                '/pb.resource.model.AdminUserModel/ShowOneById',
                request_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserShowOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserShowOneByIdOutput.FromString,
                _registered_method=True)
        self.AddOne = channel.unary_unary(
                '/pb.resource.model.AdminUserModel/AddOne',
                request_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserAddOneInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserAddOneOutput.FromString,
                _registered_method=True)
        self.EditOneById = channel.unary_unary(
                '/pb.resource.model.AdminUserModel/EditOneById',
                request_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserEditOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserEditOneByIdOutput.FromString,
                _registered_method=True)
        self.RemoveOneById = channel.unary_unary(
                '/pb.resource.model.AdminUserModel/RemoveOneById',
                request_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserRemoveOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserRemoveOneByIdOutput.FromString,
                _registered_method=True)
        self.ShowOnesByFiltersWithSortersPagination = channel.unary_unary(
                '/pb.resource.model.AdminUserModel/ShowOnesByFiltersWithSortersPagination',
                request_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserShowOnesByFiltersWithSortersPaginationInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserShowOnesByFiltersWithSortersPaginationOutput.FromString,
                _registered_method=True)
        self.TotalByFilters = channel.unary_unary(
                '/pb.resource.model.AdminUserModel/TotalByFilters',
                request_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserTotalByFiltersInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserTotalByFiltersOutput.FromString,
                _registered_method=True)


class AdminUserModelServicer:
    """Missing associated documentation comment in .proto file."""

    def ShowOneByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOnesByFiltersWithSortersPagination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TotalByFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminUserModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShowOneByName': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOneByName,
                    request_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserShowOneByNameInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserShowOneByNameOutput.SerializeToString,
            ),
            'ShowOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOneById,
                    request_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserShowOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserShowOneByIdOutput.SerializeToString,
            ),
            'AddOne': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOne,
                    request_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserAddOneInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserAddOneOutput.SerializeToString,
            ),
            'EditOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.EditOneById,
                    request_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserEditOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserEditOneByIdOutput.SerializeToString,
            ),
            'RemoveOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveOneById,
                    request_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserRemoveOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserRemoveOneByIdOutput.SerializeToString,
            ),
            'ShowOnesByFiltersWithSortersPagination': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOnesByFiltersWithSortersPagination,
                    request_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserShowOnesByFiltersWithSortersPaginationInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserShowOnesByFiltersWithSortersPaginationOutput.SerializeToString,
            ),
            'TotalByFilters': grpc.unary_unary_rpc_method_handler(
                    servicer.TotalByFilters,
                    request_deserializer=resource_dot_model_dot_admin__user__pb2.AdminUserTotalByFiltersInput.FromString,
                    response_serializer=resource_dot_model_dot_admin__user__pb2.AdminUserTotalByFiltersOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.model.AdminUserModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.model.AdminUserModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminUserModel:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShowOneByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminUserModel/ShowOneByName',
            resource_dot_model_dot_admin__user__pb2.AdminUserShowOneByNameInput.SerializeToString,
            resource_dot_model_dot_admin__user__pb2.AdminUserShowOneByNameOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminUserModel/ShowOneById',
            resource_dot_model_dot_admin__user__pb2.AdminUserShowOneByIdInput.SerializeToString,
            resource_dot_model_dot_admin__user__pb2.AdminUserShowOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminUserModel/AddOne',
            resource_dot_model_dot_admin__user__pb2.AdminUserAddOneInput.SerializeToString,
            resource_dot_model_dot_admin__user__pb2.AdminUserAddOneOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminUserModel/EditOneById',
            resource_dot_model_dot_admin__user__pb2.AdminUserEditOneByIdInput.SerializeToString,
            resource_dot_model_dot_admin__user__pb2.AdminUserEditOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminUserModel/RemoveOneById',
            resource_dot_model_dot_admin__user__pb2.AdminUserRemoveOneByIdInput.SerializeToString,
            resource_dot_model_dot_admin__user__pb2.AdminUserRemoveOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOnesByFiltersWithSortersPagination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminUserModel/ShowOnesByFiltersWithSortersPagination',
            resource_dot_model_dot_admin__user__pb2.AdminUserShowOnesByFiltersWithSortersPaginationInput.SerializeToString,
            resource_dot_model_dot_admin__user__pb2.AdminUserShowOnesByFiltersWithSortersPaginationOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TotalByFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AdminUserModel/TotalByFilters',
            resource_dot_model_dot_admin__user__pb2.AdminUserTotalByFiltersInput.SerializeToString,
            resource_dot_model_dot_admin__user__pb2.AdminUserTotalByFiltersOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
