# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.model import app_user_pb2 as resource_dot_model_dot_app__user__pb2


class AppUserModelStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddAppUser = channel.unary_unary(
                '/pb.resource.model.AppUserModel/AddAppUser',
                request_serializer=resource_dot_model_dot_app__user__pb2.AppUserAddOneInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_app__user__pb2.AppUserAddOneOutput.FromString,
                _registered_method=True)
        self.ShowOneByName = channel.unary_unary(
                '/pb.resource.model.AppUserModel/ShowOneByName',
                request_serializer=resource_dot_model_dot_app__user__pb2.AppUserShowOneByNameInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_app__user__pb2.AppUserShowOneByNameOutput.FromString,
                _registered_method=True)
        self.ShowOneById = channel.unary_unary(
                '/pb.resource.model.AppUserModel/ShowOneById',
                request_serializer=resource_dot_model_dot_app__user__pb2.AppUserShowOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_app__user__pb2.AppUserShowOneByIdOutput.FromString,
                _registered_method=True)
        self.IncreaseBalance = channel.unary_unary(
                '/pb.resource.model.AppUserModel/IncreaseBalance',
                request_serializer=resource_dot_model_dot_app__user__pb2.AppUserIncreaseBalanceInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_app__user__pb2.AppUserIncreaseBalanceOutput.FromString,
                _registered_method=True)


class AppUserModelServicer:
    """Missing associated documentation comment in .proto file."""

    def AddAppUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOneByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncreaseBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppUserModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddAppUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAppUser,
                    request_deserializer=resource_dot_model_dot_app__user__pb2.AppUserAddOneInput.FromString,
                    response_serializer=resource_dot_model_dot_app__user__pb2.AppUserAddOneOutput.SerializeToString,
            ),
            'ShowOneByName': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOneByName,
                    request_deserializer=resource_dot_model_dot_app__user__pb2.AppUserShowOneByNameInput.FromString,
                    response_serializer=resource_dot_model_dot_app__user__pb2.AppUserShowOneByNameOutput.SerializeToString,
            ),
            'ShowOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOneById,
                    request_deserializer=resource_dot_model_dot_app__user__pb2.AppUserShowOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_app__user__pb2.AppUserShowOneByIdOutput.SerializeToString,
            ),
            'IncreaseBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.IncreaseBalance,
                    request_deserializer=resource_dot_model_dot_app__user__pb2.AppUserIncreaseBalanceInput.FromString,
                    response_serializer=resource_dot_model_dot_app__user__pb2.AppUserIncreaseBalanceOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.model.AppUserModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.model.AppUserModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppUserModel:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddAppUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AppUserModel/AddAppUser',
            resource_dot_model_dot_app__user__pb2.AppUserAddOneInput.SerializeToString,
            resource_dot_model_dot_app__user__pb2.AppUserAddOneOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOneByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AppUserModel/ShowOneByName',
            resource_dot_model_dot_app__user__pb2.AppUserShowOneByNameInput.SerializeToString,
            resource_dot_model_dot_app__user__pb2.AppUserShowOneByNameOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AppUserModel/ShowOneById',
            resource_dot_model_dot_app__user__pb2.AppUserShowOneByIdInput.SerializeToString,
            resource_dot_model_dot_app__user__pb2.AppUserShowOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncreaseBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.AppUserModel/IncreaseBalance',
            resource_dot_model_dot_app__user__pb2.AppUserIncreaseBalanceInput.SerializeToString,
            resource_dot_model_dot_app__user__pb2.AppUserIncreaseBalanceOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
