# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/model/app_user.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'resource/model/app_user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dresource/model/app_user.proto\x12\x11pb.resource.model\x1a\x0c\x63ommon.proto\"E\n\x12\x41ppUserAddOneInput\x12/\n\x08variable\x18\x01 \x01(\x0b\x32\x13.pb.AppUserVariableR\x08variable\")\n\x13\x41ppUserAddOneOutput\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"/\n\x19\x41ppUserShowOneByNameInput\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"D\n\x1a\x41ppUserShowOneByNameOutput\x12&\n\x08\x61pp_user\x18\x01 \x01(\x0b\x32\x0b.pb.AppUserR\x07\x61ppUser\")\n\x17\x41ppUserShowOneByIdInput\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\"B\n\x18\x41ppUserShowOneByIdOutput\x12&\n\x08\x61pp_user\x18\x01 \x01(\x0b\x32\x0b.pb.AppUserR\x07\x61ppUser\"E\n\x1b\x41ppUserIncreaseBalanceInput\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n\x06\x61mount\x18\x02 \x01(\x04R\x06\x61mount\"\x1e\n\x1c\x41ppUserIncreaseBalanceOutput2\xb5\x03\n\x0c\x41ppUserModel\x12[\n\nAddAppUser\x12%.pb.resource.model.AppUserAddOneInput\x1a&.pb.resource.model.AppUserAddOneOutput\x12l\n\rShowOneByName\x12,.pb.resource.model.AppUserShowOneByNameInput\x1a-.pb.resource.model.AppUserShowOneByNameOutput\x12\x66\n\x0bShowOneById\x12*.pb.resource.model.AppUserShowOneByIdInput\x1a+.pb.resource.model.AppUserShowOneByIdOutput\x12r\n\x0fIncreaseBalance\x12..pb.resource.model.AppUserIncreaseBalanceInput\x1a/.pb.resource.model.AppUserIncreaseBalanceOutputB\xc8\x01\n\x15\x63om.pb.resource.modelB\x0c\x41ppUserProtoP\x01Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/model\xa2\x02\x03PRM\xaa\x02\x11Pb.Resource.Model\xca\x02\x11Pb\\Resource\\Model\xe2\x02\x1dPb\\Resource\\Model\\GPBMetadata\xea\x02\x13Pb::Resource::Modelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.model.app_user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.pb.resource.modelB\014AppUserProtoP\001Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/model\242\002\003PRM\252\002\021Pb.Resource.Model\312\002\021Pb\\Resource\\Model\342\002\035Pb\\Resource\\Model\\GPBMetadata\352\002\023Pb::Resource::Model'
  _globals['_APPUSERADDONEINPUT']._serialized_start=66
  _globals['_APPUSERADDONEINPUT']._serialized_end=135
  _globals['_APPUSERADDONEOUTPUT']._serialized_start=137
  _globals['_APPUSERADDONEOUTPUT']._serialized_end=178
  _globals['_APPUSERSHOWONEBYNAMEINPUT']._serialized_start=180
  _globals['_APPUSERSHOWONEBYNAMEINPUT']._serialized_end=227
  _globals['_APPUSERSHOWONEBYNAMEOUTPUT']._serialized_start=229
  _globals['_APPUSERSHOWONEBYNAMEOUTPUT']._serialized_end=297
  _globals['_APPUSERSHOWONEBYIDINPUT']._serialized_start=299
  _globals['_APPUSERSHOWONEBYIDINPUT']._serialized_end=340
  _globals['_APPUSERSHOWONEBYIDOUTPUT']._serialized_start=342
  _globals['_APPUSERSHOWONEBYIDOUTPUT']._serialized_end=408
  _globals['_APPUSERINCREASEBALANCEINPUT']._serialized_start=410
  _globals['_APPUSERINCREASEBALANCEINPUT']._serialized_end=479
  _globals['_APPUSERINCREASEBALANCEOUTPUT']._serialized_start=481
  _globals['_APPUSERINCREASEBALANCEOUTPUT']._serialized_end=511
  _globals['_APPUSERMODEL']._serialized_start=514
  _globals['_APPUSERMODEL']._serialized_end=951
# @@protoc_insertion_point(module_scope)
