# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.model import game_type_pb2 as resource_dot_model_dot_game__type__pb2


class GameTypeModelStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddOne = channel.unary_unary(
                '/pb.resource.model.GameTypeModel/AddOne',
                request_serializer=resource_dot_model_dot_game__type__pb2.GameTypeAddOneInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_game__type__pb2.GameTypeAddOneOutput.FromString,
                _registered_method=True)
        self.EditOneById = channel.unary_unary(
                '/pb.resource.model.GameTypeModel/EditOneById',
                request_serializer=resource_dot_model_dot_game__type__pb2.GameTypeEditOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_game__type__pb2.GameTypeEditOneByIdOutput.FromString,
                _registered_method=True)
        self.RemoveOneById = channel.unary_unary(
                '/pb.resource.model.GameTypeModel/RemoveOneById',
                request_serializer=resource_dot_model_dot_game__type__pb2.GameTypeRemoveOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_game__type__pb2.GameTypeRemoveOneByIdOutput.FromString,
                _registered_method=True)
        self.TotalByFilters = channel.unary_unary(
                '/pb.resource.model.GameTypeModel/TotalByFilters',
                request_serializer=resource_dot_model_dot_game__type__pb2.GameTypeTotalByFiltersInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_game__type__pb2.GameTypeTotalByFiltersOutput.FromString,
                _registered_method=True)


class GameTypeModelServicer:
    """Missing associated documentation comment in .proto file."""

    def AddOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TotalByFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameTypeModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddOne': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOne,
                    request_deserializer=resource_dot_model_dot_game__type__pb2.GameTypeAddOneInput.FromString,
                    response_serializer=resource_dot_model_dot_game__type__pb2.GameTypeAddOneOutput.SerializeToString,
            ),
            'EditOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.EditOneById,
                    request_deserializer=resource_dot_model_dot_game__type__pb2.GameTypeEditOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_game__type__pb2.GameTypeEditOneByIdOutput.SerializeToString,
            ),
            'RemoveOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveOneById,
                    request_deserializer=resource_dot_model_dot_game__type__pb2.GameTypeRemoveOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_game__type__pb2.GameTypeRemoveOneByIdOutput.SerializeToString,
            ),
            'TotalByFilters': grpc.unary_unary_rpc_method_handler(
                    servicer.TotalByFilters,
                    request_deserializer=resource_dot_model_dot_game__type__pb2.GameTypeTotalByFiltersInput.FromString,
                    response_serializer=resource_dot_model_dot_game__type__pb2.GameTypeTotalByFiltersOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.model.GameTypeModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.model.GameTypeModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameTypeModel:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.GameTypeModel/AddOne',
            resource_dot_model_dot_game__type__pb2.GameTypeAddOneInput.SerializeToString,
            resource_dot_model_dot_game__type__pb2.GameTypeAddOneOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.GameTypeModel/EditOneById',
            resource_dot_model_dot_game__type__pb2.GameTypeEditOneByIdInput.SerializeToString,
            resource_dot_model_dot_game__type__pb2.GameTypeEditOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.GameTypeModel/RemoveOneById',
            resource_dot_model_dot_game__type__pb2.GameTypeRemoveOneByIdInput.SerializeToString,
            resource_dot_model_dot_game__type__pb2.GameTypeRemoveOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TotalByFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.GameTypeModel/TotalByFilters',
            resource_dot_model_dot_game__type__pb2.GameTypeTotalByFiltersInput.SerializeToString,
            resource_dot_model_dot_game__type__pb2.GameTypeTotalByFiltersOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
