# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/model/game.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'resource/model/game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19resource/model/game.proto\x12\x11pb.resource.model\x1a\x0c\x63ommon.proto\"?\n\x0fGameAddOneInput\x12,\n\x08variable\x18\x01 \x01(\x0b\x32\x10.pb.GameVariableR\x08variable\"0\n\x10GameAddOneOutput\x12\x1c\n\x04game\x18\x01 \x01(\x0b\x32\x08.pb.GameR\x04game\")\n\x15GameShowOneByKeyInput\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\"6\n\x16GameShowOneByKeyOutput\x12\x1c\n\x04game\x18\x01 \x01(\x0b\x32\x08.pb.GameR\x04game\"T\n\x14GameEditOneByIdInput\x12,\n\x08variable\x18\x01 \x01(\x0b\x32\x10.pb.GameVariableR\x08variable\x12\x0e\n\x02id\x18\x02 \x01(\x04R\x02id\"\x17\n\x15GameEditOneByIdOutput\"(\n\x16GameRemoveOneByIdInput\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\"\x19\n\x17GameRemoveOneByIdOutput\"?\n\x17GameTotalByFiltersInput\x12$\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\n.pb.FilterR\x07\x66ilters\"0\n\x18GameTotalByFiltersOutput\x12\x14\n\x05total\x18\x01 \x01(\x04R\x05total2\xf8\x03\n\tGameModel\x12Q\n\x06\x41\x64\x64One\x12\".pb.resource.model.GameAddOneInput\x1a#.pb.resource.model.GameAddOneOutput\x12\x63\n\x0cShowOneByKey\x12(.pb.resource.model.GameShowOneByKeyInput\x1a).pb.resource.model.GameShowOneByKeyOutput\x12`\n\x0b\x45\x64itOneById\x12\'.pb.resource.model.GameEditOneByIdInput\x1a(.pb.resource.model.GameEditOneByIdOutput\x12\x66\n\rRemoveOneById\x12).pb.resource.model.GameRemoveOneByIdInput\x1a*.pb.resource.model.GameRemoveOneByIdOutput\x12i\n\x0eTotalByFilters\x12*.pb.resource.model.GameTotalByFiltersInput\x1a+.pb.resource.model.GameTotalByFiltersOutputB\xc5\x01\n\x15\x63om.pb.resource.modelB\tGameProtoP\x01Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/model\xa2\x02\x03PRM\xaa\x02\x11Pb.Resource.Model\xca\x02\x11Pb\\Resource\\Model\xe2\x02\x1dPb\\Resource\\Model\\GPBMetadata\xea\x02\x13Pb::Resource::Modelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.model.game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.pb.resource.modelB\tGameProtoP\001Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/model\242\002\003PRM\252\002\021Pb.Resource.Model\312\002\021Pb\\Resource\\Model\342\002\035Pb\\Resource\\Model\\GPBMetadata\352\002\023Pb::Resource::Model'
  _globals['_GAMEADDONEINPUT']._serialized_start=62
  _globals['_GAMEADDONEINPUT']._serialized_end=125
  _globals['_GAMEADDONEOUTPUT']._serialized_start=127
  _globals['_GAMEADDONEOUTPUT']._serialized_end=175
  _globals['_GAMESHOWONEBYKEYINPUT']._serialized_start=177
  _globals['_GAMESHOWONEBYKEYINPUT']._serialized_end=218
  _globals['_GAMESHOWONEBYKEYOUTPUT']._serialized_start=220
  _globals['_GAMESHOWONEBYKEYOUTPUT']._serialized_end=274
  _globals['_GAMEEDITONEBYIDINPUT']._serialized_start=276
  _globals['_GAMEEDITONEBYIDINPUT']._serialized_end=360
  _globals['_GAMEEDITONEBYIDOUTPUT']._serialized_start=362
  _globals['_GAMEEDITONEBYIDOUTPUT']._serialized_end=385
  _globals['_GAMEREMOVEONEBYIDINPUT']._serialized_start=387
  _globals['_GAMEREMOVEONEBYIDINPUT']._serialized_end=427
  _globals['_GAMEREMOVEONEBYIDOUTPUT']._serialized_start=429
  _globals['_GAMEREMOVEONEBYIDOUTPUT']._serialized_end=454
  _globals['_GAMETOTALBYFILTERSINPUT']._serialized_start=456
  _globals['_GAMETOTALBYFILTERSINPUT']._serialized_end=519
  _globals['_GAMETOTALBYFILTERSOUTPUT']._serialized_start=521
  _globals['_GAMETOTALBYFILTERSOUTPUT']._serialized_end=569
  _globals['_GAMEMODEL']._serialized_start=572
  _globals['_GAMEMODEL']._serialized_end=1076
# @@protoc_insertion_point(module_scope)
