# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/model/game_type.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'resource/model/game_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eresource/model/game_type.proto\x12\x11pb.resource.model\x1a\x0c\x63ommon.proto\"G\n\x13GameTypeAddOneInput\x12\x30\n\x08variable\x18\x01 \x01(\x0b\x32\x14.pb.GameTypeVariableR\x08variable\"A\n\x14GameTypeAddOneOutput\x12)\n\tgame_type\x18\x01 \x01(\x0b\x32\x0c.pb.GameTypeR\x08gameType\"\\\n\x18GameTypeEditOneByIdInput\x12\x30\n\x08variable\x18\x01 \x01(\x0b\x32\x14.pb.GameTypeVariableR\x08variable\x12\x0e\n\x02id\x18\x02 \x01(\x04R\x02id\"\x1b\n\x19GameTypeEditOneByIdOutput\",\n\x1aGameTypeRemoveOneByIdInput\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\"\x1d\n\x1bGameTypeRemoveOneByIdOutput\"C\n\x1bGameTypeTotalByFiltersInput\x12$\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\n.pb.FilterR\x07\x66ilters\"4\n\x1cGameTypeTotalByFiltersOutput\x12\x14\n\x05total\x18\x01 \x01(\x04R\x05total2\xb7\x03\n\rGameTypeModel\x12Y\n\x06\x41\x64\x64One\x12&.pb.resource.model.GameTypeAddOneInput\x1a\'.pb.resource.model.GameTypeAddOneOutput\x12h\n\x0b\x45\x64itOneById\x12+.pb.resource.model.GameTypeEditOneByIdInput\x1a,.pb.resource.model.GameTypeEditOneByIdOutput\x12n\n\rRemoveOneById\x12-.pb.resource.model.GameTypeRemoveOneByIdInput\x1a..pb.resource.model.GameTypeRemoveOneByIdOutput\x12q\n\x0eTotalByFilters\x12..pb.resource.model.GameTypeTotalByFiltersInput\x1a/.pb.resource.model.GameTypeTotalByFiltersOutputB\xc9\x01\n\x15\x63om.pb.resource.modelB\rGameTypeProtoP\x01Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/model\xa2\x02\x03PRM\xaa\x02\x11Pb.Resource.Model\xca\x02\x11Pb\\Resource\\Model\xe2\x02\x1dPb\\Resource\\Model\\GPBMetadata\xea\x02\x13Pb::Resource::Modelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.model.game_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.pb.resource.modelB\rGameTypeProtoP\001Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/model\242\002\003PRM\252\002\021Pb.Resource.Model\312\002\021Pb\\Resource\\Model\342\002\035Pb\\Resource\\Model\\GPBMetadata\352\002\023Pb::Resource::Model'
  _globals['_GAMETYPEADDONEINPUT']._serialized_start=67
  _globals['_GAMETYPEADDONEINPUT']._serialized_end=138
  _globals['_GAMETYPEADDONEOUTPUT']._serialized_start=140
  _globals['_GAMETYPEADDONEOUTPUT']._serialized_end=205
  _globals['_GAMETYPEEDITONEBYIDINPUT']._serialized_start=207
  _globals['_GAMETYPEEDITONEBYIDINPUT']._serialized_end=299
  _globals['_GAMETYPEEDITONEBYIDOUTPUT']._serialized_start=301
  _globals['_GAMETYPEEDITONEBYIDOUTPUT']._serialized_end=328
  _globals['_GAMETYPEREMOVEONEBYIDINPUT']._serialized_start=330
  _globals['_GAMETYPEREMOVEONEBYIDINPUT']._serialized_end=374
  _globals['_GAMETYPEREMOVEONEBYIDOUTPUT']._serialized_start=376
  _globals['_GAMETYPEREMOVEONEBYIDOUTPUT']._serialized_end=405
  _globals['_GAMETYPETOTALBYFILTERSINPUT']._serialized_start=407
  _globals['_GAMETYPETOTALBYFILTERSINPUT']._serialized_end=474
  _globals['_GAMETYPETOTALBYFILTERSOUTPUT']._serialized_start=476
  _globals['_GAMETYPETOTALBYFILTERSOUTPUT']._serialized_end=528
  _globals['_GAMETYPEMODEL']._serialized_start=531
  _globals['_GAMETYPEMODEL']._serialized_end=970
# @@protoc_insertion_point(module_scope)
