# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.model import game_pb2 as resource_dot_model_dot_game__pb2


class GameModelStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddOne = channel.unary_unary(
                '/pb.resource.model.GameModel/AddOne',
                request_serializer=resource_dot_model_dot_game__pb2.GameAddOneInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_game__pb2.GameAddOneOutput.FromString,
                _registered_method=True)
        self.ShowOneByKey = channel.unary_unary(
                '/pb.resource.model.GameModel/ShowOneByKey',
                request_serializer=resource_dot_model_dot_game__pb2.GameShowOneByKeyInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_game__pb2.GameShowOneByKeyOutput.FromString,
                _registered_method=True)
        self.EditOneById = channel.unary_unary(
                '/pb.resource.model.GameModel/EditOneById',
                request_serializer=resource_dot_model_dot_game__pb2.GameEditOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_game__pb2.GameEditOneByIdOutput.FromString,
                _registered_method=True)
        self.RemoveOneById = channel.unary_unary(
                '/pb.resource.model.GameModel/RemoveOneById',
                request_serializer=resource_dot_model_dot_game__pb2.GameRemoveOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_game__pb2.GameRemoveOneByIdOutput.FromString,
                _registered_method=True)
        self.TotalByFilters = channel.unary_unary(
                '/pb.resource.model.GameModel/TotalByFilters',
                request_serializer=resource_dot_model_dot_game__pb2.GameTotalByFiltersInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_game__pb2.GameTotalByFiltersOutput.FromString,
                _registered_method=True)


class GameModelServicer:
    """Missing associated documentation comment in .proto file."""

    def AddOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowOneByKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TotalByFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddOne': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOne,
                    request_deserializer=resource_dot_model_dot_game__pb2.GameAddOneInput.FromString,
                    response_serializer=resource_dot_model_dot_game__pb2.GameAddOneOutput.SerializeToString,
            ),
            'ShowOneByKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowOneByKey,
                    request_deserializer=resource_dot_model_dot_game__pb2.GameShowOneByKeyInput.FromString,
                    response_serializer=resource_dot_model_dot_game__pb2.GameShowOneByKeyOutput.SerializeToString,
            ),
            'EditOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.EditOneById,
                    request_deserializer=resource_dot_model_dot_game__pb2.GameEditOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_game__pb2.GameEditOneByIdOutput.SerializeToString,
            ),
            'RemoveOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveOneById,
                    request_deserializer=resource_dot_model_dot_game__pb2.GameRemoveOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_game__pb2.GameRemoveOneByIdOutput.SerializeToString,
            ),
            'TotalByFilters': grpc.unary_unary_rpc_method_handler(
                    servicer.TotalByFilters,
                    request_deserializer=resource_dot_model_dot_game__pb2.GameTotalByFiltersInput.FromString,
                    response_serializer=resource_dot_model_dot_game__pb2.GameTotalByFiltersOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.model.GameModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.model.GameModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameModel:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.GameModel/AddOne',
            resource_dot_model_dot_game__pb2.GameAddOneInput.SerializeToString,
            resource_dot_model_dot_game__pb2.GameAddOneOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowOneByKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.GameModel/ShowOneByKey',
            resource_dot_model_dot_game__pb2.GameShowOneByKeyInput.SerializeToString,
            resource_dot_model_dot_game__pb2.GameShowOneByKeyOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.GameModel/EditOneById',
            resource_dot_model_dot_game__pb2.GameEditOneByIdInput.SerializeToString,
            resource_dot_model_dot_game__pb2.GameEditOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.GameModel/RemoveOneById',
            resource_dot_model_dot_game__pb2.GameRemoveOneByIdInput.SerializeToString,
            resource_dot_model_dot_game__pb2.GameRemoveOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TotalByFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.GameModel/TotalByFilters',
            resource_dot_model_dot_game__pb2.GameTotalByFiltersInput.SerializeToString,
            resource_dot_model_dot_game__pb2.GameTotalByFiltersOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
