# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/model/table.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'resource/model/table.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aresource/model/table.proto\x12\x11pb.resource.model\x1a\x0c\x63ommon.proto\"A\n\x10TableAddOneInput\x12-\n\x08variable\x18\x01 \x01(\x0b\x32\x11.pb.TableVariableR\x08variable\"\x13\n\x11TableAddOneOutput\"V\n\x15TableEditOneByIdInput\x12-\n\x08variable\x18\x01 \x01(\x0b\x32\x11.pb.TableVariableR\x08variable\x12\x0e\n\x02id\x18\x02 \x01(\x04R\x02id\"\x18\n\x16TableEditOneByIdOutput\")\n\x17TableRemoveOneByIdInput\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\"\x1a\n\x18TableRemoveOneByIdOutput\"@\n\x18TableTotalByFiltersInput\x12$\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\n.pb.FilterR\x07\x66ilters\"1\n\x19TableTotalByFiltersOutput\x12\x14\n\x05total\x18\x01 \x01(\x04R\x05total2\x9c\x03\n\nTableModel\x12S\n\x06\x41\x64\x64One\x12#.pb.resource.model.TableAddOneInput\x1a$.pb.resource.model.TableAddOneOutput\x12\x62\n\x0b\x45\x64itOneById\x12(.pb.resource.model.TableEditOneByIdInput\x1a).pb.resource.model.TableEditOneByIdOutput\x12h\n\rRemoveOneById\x12*.pb.resource.model.TableRemoveOneByIdInput\x1a+.pb.resource.model.TableRemoveOneByIdOutput\x12k\n\x0eTotalByFilters\x12+.pb.resource.model.TableTotalByFiltersInput\x1a,.pb.resource.model.TableTotalByFiltersOutputB\xc6\x01\n\x15\x63om.pb.resource.modelB\nTableProtoP\x01Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/model\xa2\x02\x03PRM\xaa\x02\x11Pb.Resource.Model\xca\x02\x11Pb\\Resource\\Model\xe2\x02\x1dPb\\Resource\\Model\\GPBMetadata\xea\x02\x13Pb::Resource::Modelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.model.table_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.pb.resource.modelB\nTableProtoP\001Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/model\242\002\003PRM\252\002\021Pb.Resource.Model\312\002\021Pb\\Resource\\Model\342\002\035Pb\\Resource\\Model\\GPBMetadata\352\002\023Pb::Resource::Model'
  _globals['_TABLEADDONEINPUT']._serialized_start=63
  _globals['_TABLEADDONEINPUT']._serialized_end=128
  _globals['_TABLEADDONEOUTPUT']._serialized_start=130
  _globals['_TABLEADDONEOUTPUT']._serialized_end=149
  _globals['_TABLEEDITONEBYIDINPUT']._serialized_start=151
  _globals['_TABLEEDITONEBYIDINPUT']._serialized_end=237
  _globals['_TABLEEDITONEBYIDOUTPUT']._serialized_start=239
  _globals['_TABLEEDITONEBYIDOUTPUT']._serialized_end=263
  _globals['_TABLEREMOVEONEBYIDINPUT']._serialized_start=265
  _globals['_TABLEREMOVEONEBYIDINPUT']._serialized_end=306
  _globals['_TABLEREMOVEONEBYIDOUTPUT']._serialized_start=308
  _globals['_TABLEREMOVEONEBYIDOUTPUT']._serialized_end=334
  _globals['_TABLETOTALBYFILTERSINPUT']._serialized_start=336
  _globals['_TABLETOTALBYFILTERSINPUT']._serialized_end=400
  _globals['_TABLETOTALBYFILTERSOUTPUT']._serialized_start=402
  _globals['_TABLETOTALBYFILTERSOUTPUT']._serialized_end=451
  _globals['_TABLEMODEL']._serialized_start=454
  _globals['_TABLEMODEL']._serialized_end=866
# @@protoc_insertion_point(module_scope)
