# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.model import table_pb2 as resource_dot_model_dot_table__pb2


class TableModelStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddOne = channel.unary_unary(
                '/pb.resource.model.TableModel/AddOne',
                request_serializer=resource_dot_model_dot_table__pb2.TableAddOneInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_table__pb2.TableAddOneOutput.FromString,
                _registered_method=True)
        self.EditOneById = channel.unary_unary(
                '/pb.resource.model.TableModel/EditOneById',
                request_serializer=resource_dot_model_dot_table__pb2.TableEditOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_table__pb2.TableEditOneByIdOutput.FromString,
                _registered_method=True)
        self.RemoveOneById = channel.unary_unary(
                '/pb.resource.model.TableModel/RemoveOneById',
                request_serializer=resource_dot_model_dot_table__pb2.TableRemoveOneByIdInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_table__pb2.TableRemoveOneByIdOutput.FromString,
                _registered_method=True)
        self.TotalByFilters = channel.unary_unary(
                '/pb.resource.model.TableModel/TotalByFilters',
                request_serializer=resource_dot_model_dot_table__pb2.TableTotalByFiltersInput.SerializeToString,
                response_deserializer=resource_dot_model_dot_table__pb2.TableTotalByFiltersOutput.FromString,
                _registered_method=True)


class TableModelServicer:
    """Missing associated documentation comment in .proto file."""

    def AddOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveOneById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TotalByFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TableModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddOne': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOne,
                    request_deserializer=resource_dot_model_dot_table__pb2.TableAddOneInput.FromString,
                    response_serializer=resource_dot_model_dot_table__pb2.TableAddOneOutput.SerializeToString,
            ),
            'EditOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.EditOneById,
                    request_deserializer=resource_dot_model_dot_table__pb2.TableEditOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_table__pb2.TableEditOneByIdOutput.SerializeToString,
            ),
            'RemoveOneById': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveOneById,
                    request_deserializer=resource_dot_model_dot_table__pb2.TableRemoveOneByIdInput.FromString,
                    response_serializer=resource_dot_model_dot_table__pb2.TableRemoveOneByIdOutput.SerializeToString,
            ),
            'TotalByFilters': grpc.unary_unary_rpc_method_handler(
                    servicer.TotalByFilters,
                    request_deserializer=resource_dot_model_dot_table__pb2.TableTotalByFiltersInput.FromString,
                    response_serializer=resource_dot_model_dot_table__pb2.TableTotalByFiltersOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.model.TableModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.model.TableModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TableModel:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.TableModel/AddOne',
            resource_dot_model_dot_table__pb2.TableAddOneInput.SerializeToString,
            resource_dot_model_dot_table__pb2.TableAddOneOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.TableModel/EditOneById',
            resource_dot_model_dot_table__pb2.TableEditOneByIdInput.SerializeToString,
            resource_dot_model_dot_table__pb2.TableEditOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveOneById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.TableModel/RemoveOneById',
            resource_dot_model_dot_table__pb2.TableRemoveOneByIdInput.SerializeToString,
            resource_dot_model_dot_table__pb2.TableRemoveOneByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TotalByFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.model.TableModel/TotalByFilters',
            resource_dot_model_dot_table__pb2.TableTotalByFiltersInput.SerializeToString,
            resource_dot_model_dot_table__pb2.TableTotalByFiltersOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
