# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.ir.table.inference.equipment import die_pb2 as ir_dot_table_dot_inference_dot_equipment_dot_die__pb2


class DieServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeDie = channel.unary_unary(
                '/pb.ir.table.inference.equipment.DieService/RecognizeDie',
                request_serializer=ir_dot_table_dot_inference_dot_equipment_dot_die__pb2.RecognizeDieRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_equipment_dot_die__pb2.RecognizeDieResponse.FromString,
                _registered_method=True)


class DieServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RecognizeDie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeDie': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeDie,
                    request_deserializer=ir_dot_table_dot_inference_dot_equipment_dot_die__pb2.RecognizeDieRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_equipment_dot_die__pb2.RecognizeDieResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ir.table.inference.equipment.DieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.ir.table.inference.equipment.DieService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DieService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizeDie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.equipment.DieService/RecognizeDie',
            ir_dot_table_dot_inference_dot_equipment_dot_die__pb2.RecognizeDieRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_equipment_dot_die__pb2.RecognizeDieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
