# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ir/table/inference/equipment/disk.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'ir/table/inference/equipment/disk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb.ir import ir_pb2 as ir_dot_ir__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ir/table/inference/equipment/disk.proto\x12\x1fpb.ir.table.inference.equipment\x1a\x0bir/ir.proto\"\x16\n\x14RecognizeDiskRequest\":\n\x15RecognizeDiskResponse\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x0b.pb.ir.DiskR\x05items2\x8d\x01\n\x0b\x44iskService\x12~\n\rRecognizeDisk\x12\x35.pb.ir.table.inference.equipment.RecognizeDiskRequest\x1a\x36.pb.ir.table.inference.equipment.RecognizeDiskResponseB\x9d\x02\n#com.pb.ir.table.inference.equipmentB\tDiskProtoP\x01ZIgithub.com/wegdevio/pk-studio-reader/pkg/api/ir/table/inference/equipment\xa2\x02\x05PITIE\xaa\x02\x1fPb.Ir.Table.Inference.Equipment\xca\x02\x1fPb\\Ir\\Table\\Inference\\Equipment\xe2\x02+Pb\\Ir\\Table\\Inference\\Equipment\\GPBMetadata\xea\x02#Pb::Ir::Table::Inference::Equipmentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ir.table.inference.equipment.disk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.pb.ir.table.inference.equipmentB\tDiskProtoP\001ZIgithub.com/wegdevio/pk-studio-reader/pkg/api/ir/table/inference/equipment\242\002\005PITIE\252\002\037Pb.Ir.Table.Inference.Equipment\312\002\037Pb\\Ir\\Table\\Inference\\Equipment\342\002+Pb\\Ir\\Table\\Inference\\Equipment\\GPBMetadata\352\002#Pb::Ir::Table::Inference::Equipment'
  _globals['_RECOGNIZEDISKREQUEST']._serialized_start=89
  _globals['_RECOGNIZEDISKREQUEST']._serialized_end=111
  _globals['_RECOGNIZEDISKRESPONSE']._serialized_start=113
  _globals['_RECOGNIZEDISKRESPONSE']._serialized_end=171
  _globals['_DISKSERVICE']._serialized_start=174
  _globals['_DISKSERVICE']._serialized_end=315
# @@protoc_insertion_point(module_scope)
