# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.ir.table.inference.equipment import poker_pb2 as ir_dot_table_dot_inference_dot_equipment_dot_poker__pb2


class PokerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizePoker = channel.unary_stream(
                '/pb.ir.table.inference.equipment.PokerService/RecognizePoker',
                request_serializer=ir_dot_table_dot_inference_dot_equipment_dot_poker__pb2.RecognizePokerRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_equipment_dot_poker__pb2.RecognizePokerResponse.FromString,
                _registered_method=True)


class PokerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RecognizePoker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizePoker': grpc.unary_stream_rpc_method_handler(
                    servicer.RecognizePoker,
                    request_deserializer=ir_dot_table_dot_inference_dot_equipment_dot_poker__pb2.RecognizePokerRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_equipment_dot_poker__pb2.RecognizePokerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ir.table.inference.equipment.PokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.ir.table.inference.equipment.PokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PokerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizePoker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pb.ir.table.inference.equipment.PokerService/RecognizePoker',
            ir_dot_table_dot_inference_dot_equipment_dot_poker__pb2.RecognizePokerRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_equipment_dot_poker__pb2.RecognizePokerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
