# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recognition/ir/inference/item/die.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'recognition/ir/inference/item/die.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb.recognition import ir_pb2 as recognition_dot_ir__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'recognition/ir/inference/item/die.proto\x12 pb.recognition.ir.inference.item\x1a\x14recognition/ir.proto\"\x1a\n\x18\x44ieRecognizeItemsRequest\"F\n\x19\x44ieRecognizeItemsResponse\x12)\n\x05items\x18\x01 \x03(\x0b\x32\x13.pb.recognition.DieR\x05items2\x98\x01\n\nDieService\x12\x89\x01\n\x0eRecognizeItems\x12:.pb.recognition.ir.inference.item.DieRecognizeItemsRequest\x1a;.pb.recognition.ir.inference.item.DieRecognizeItemsResponseB\xa2\x02\n$com.pb.recognition.ir.inference.itemB\x08\x44ieProtoP\x01ZJgithub.com/wegdevio/pk-studio-reader/pkg/api/recognition/ir/inference/item\xa2\x02\x05PRIII\xaa\x02 Pb.Recognition.Ir.Inference.Item\xca\x02 Pb\\Recognition\\Ir\\Inference\\Item\xe2\x02,Pb\\Recognition\\Ir\\Inference\\Item\\GPBMetadata\xea\x02$Pb::Recognition::Ir::Inference::Itemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recognition.ir.inference.item.die_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.pb.recognition.ir.inference.itemB\010DieProtoP\001ZJgithub.com/wegdevio/pk-studio-reader/pkg/api/recognition/ir/inference/item\242\002\005PRIII\252\002 Pb.Recognition.Ir.Inference.Item\312\002 Pb\\Recognition\\Ir\\Inference\\Item\342\002,Pb\\Recognition\\Ir\\Inference\\Item\\GPBMetadata\352\002$Pb::Recognition::Ir::Inference::Item'
  _globals['_DIERECOGNIZEITEMSREQUEST']._serialized_start=99
  _globals['_DIERECOGNIZEITEMSREQUEST']._serialized_end=125
  _globals['_DIERECOGNIZEITEMSRESPONSE']._serialized_start=127
  _globals['_DIERECOGNIZEITEMSRESPONSE']._serialized_end=197
  _globals['_DIESERVICE']._serialized_start=200
  _globals['_DIESERVICE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
