# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.recognition.ir.inference.item import poker_pb2 as recognition_dot_ir_dot_inference_dot_item_dot_poker__pb2


class PokerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeItems = channel.unary_stream(
                '/pb.recognition.ir.inference.item.PokerService/RecognizeItems',
                request_serializer=recognition_dot_ir_dot_inference_dot_item_dot_poker__pb2.PokerRecognizeItemsRequest.SerializeToString,
                response_deserializer=recognition_dot_ir_dot_inference_dot_item_dot_poker__pb2.PokerRecognizeItemsResponse.FromString,
                _registered_method=True)


class PokerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RecognizeItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeItems': grpc.unary_stream_rpc_method_handler(
                    servicer.RecognizeItems,
                    request_deserializer=recognition_dot_ir_dot_inference_dot_item_dot_poker__pb2.PokerRecognizeItemsRequest.FromString,
                    response_serializer=recognition_dot_ir_dot_inference_dot_item_dot_poker__pb2.PokerRecognizeItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.recognition.ir.inference.item.PokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.recognition.ir.inference.item.PokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PokerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizeItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pb.recognition.ir.inference.item.PokerService/RecognizeItems',
            recognition_dot_ir_dot_inference_dot_item_dot_poker__pb2.PokerRecognizeItemsRequest.SerializeToString,
            recognition_dot_ir_dot_inference_dot_item_dot_poker__pb2.PokerRecognizeItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
