# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.logic import admin_role_pb2 as resource_dot_logic_dot_admin__role__pb2


class AdminRoleLogicStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddAdminRole = channel.unary_unary(
                '/pb.resource.logic.AdminRoleLogic/AddAdminRole',
                request_serializer=resource_dot_logic_dot_admin__role__pb2.AdminRoleAddAdminRoleInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_admin__role__pb2.AdminRoleAddAdminRoleOutput.FromString,
                _registered_method=True)


class AdminRoleLogicServicer:
    """Missing associated documentation comment in .proto file."""

    def AddAdminRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminRoleLogicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddAdminRole': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAdminRole,
                    request_deserializer=resource_dot_logic_dot_admin__role__pb2.AdminRoleAddAdminRoleInput.FromString,
                    response_serializer=resource_dot_logic_dot_admin__role__pb2.AdminRoleAddAdminRoleOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.logic.AdminRoleLogic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.logic.AdminRoleLogic', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminRoleLogic:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddAdminRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AdminRoleLogic/AddAdminRole',
            resource_dot_logic_dot_admin__role__pb2.AdminRoleAddAdminRoleInput.SerializeToString,
            resource_dot_logic_dot_admin__role__pb2.AdminRoleAddAdminRoleOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
