# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.logic import admin_permission_group_pb2 as resource_dot_logic_dot_admin__permission__group__pb2


class AdminPermissionGroupLogicStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddAdminPermissionGroup = channel.unary_unary(
                '/pb.resource.logic.AdminPermissionGroupLogic/AddAdminPermissionGroup',
                request_serializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupAddAdminPermissionGroupInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupAddAdminPermissionGroupOutput.FromString,
                _registered_method=True)
        self.EditAdminPermissionGroupById = channel.unary_unary(
                '/pb.resource.logic.AdminPermissionGroupLogic/EditAdminPermissionGroupById',
                request_serializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupEditAdminPermissionGroupByIdInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupEditAdminPermissionGroupByIdOutput.FromString,
                _registered_method=True)
        self.ShowTree = channel.unary_unary(
                '/pb.resource.logic.AdminPermissionGroupLogic/ShowTree',
                request_serializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowTreeInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowTreeOutput.FromString,
                _registered_method=True)
        self.ShowAdminPermissionGroupById = channel.unary_unary(
                '/pb.resource.logic.AdminPermissionGroupLogic/ShowAdminPermissionGroupById',
                request_serializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupByIdInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupByIdOutput.FromString,
                _registered_method=True)
        self.ShowAdminPermissionGroups = channel.unary_unary(
                '/pb.resource.logic.AdminPermissionGroupLogic/ShowAdminPermissionGroups',
                request_serializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupsInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupsOutput.FromString,
                _registered_method=True)
        self.ShowAdminPermissionGroupsTotalByFiltersWithSortersPagination = channel.unary_unary(
                '/pb.resource.logic.AdminPermissionGroupLogic/ShowAdminPermissionGroupsTotalByFiltersWithSortersPagination',
                request_serializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupsTotalByFiltersWithSortersPaginationInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupsTotalByFiltersWithSortersPaginationOutput.FromString,
                _registered_method=True)


class AdminPermissionGroupLogicServicer:
    """Missing associated documentation comment in .proto file."""

    def AddAdminPermissionGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditAdminPermissionGroupById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowAdminPermissionGroupById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowAdminPermissionGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowAdminPermissionGroupsTotalByFiltersWithSortersPagination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminPermissionGroupLogicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddAdminPermissionGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAdminPermissionGroup,
                    request_deserializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupAddAdminPermissionGroupInput.FromString,
                    response_serializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupAddAdminPermissionGroupOutput.SerializeToString,
            ),
            'EditAdminPermissionGroupById': grpc.unary_unary_rpc_method_handler(
                    servicer.EditAdminPermissionGroupById,
                    request_deserializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupEditAdminPermissionGroupByIdInput.FromString,
                    response_serializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupEditAdminPermissionGroupByIdOutput.SerializeToString,
            ),
            'ShowTree': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowTree,
                    request_deserializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowTreeInput.FromString,
                    response_serializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowTreeOutput.SerializeToString,
            ),
            'ShowAdminPermissionGroupById': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowAdminPermissionGroupById,
                    request_deserializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupByIdInput.FromString,
                    response_serializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupByIdOutput.SerializeToString,
            ),
            'ShowAdminPermissionGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowAdminPermissionGroups,
                    request_deserializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupsInput.FromString,
                    response_serializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupsOutput.SerializeToString,
            ),
            'ShowAdminPermissionGroupsTotalByFiltersWithSortersPagination': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowAdminPermissionGroupsTotalByFiltersWithSortersPagination,
                    request_deserializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupsTotalByFiltersWithSortersPaginationInput.FromString,
                    response_serializer=resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupsTotalByFiltersWithSortersPaginationOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.logic.AdminPermissionGroupLogic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.logic.AdminPermissionGroupLogic', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminPermissionGroupLogic:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddAdminPermissionGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AdminPermissionGroupLogic/AddAdminPermissionGroup',
            resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupAddAdminPermissionGroupInput.SerializeToString,
            resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupAddAdminPermissionGroupOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditAdminPermissionGroupById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AdminPermissionGroupLogic/EditAdminPermissionGroupById',
            resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupEditAdminPermissionGroupByIdInput.SerializeToString,
            resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupEditAdminPermissionGroupByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AdminPermissionGroupLogic/ShowTree',
            resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowTreeInput.SerializeToString,
            resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowTreeOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowAdminPermissionGroupById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AdminPermissionGroupLogic/ShowAdminPermissionGroupById',
            resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupByIdInput.SerializeToString,
            resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowAdminPermissionGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AdminPermissionGroupLogic/ShowAdminPermissionGroups',
            resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupsInput.SerializeToString,
            resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupsOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowAdminPermissionGroupsTotalByFiltersWithSortersPagination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AdminPermissionGroupLogic/ShowAdminPermissionGroupsTotalByFiltersWithSortersPagination',
            resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupsTotalByFiltersWithSortersPaginationInput.SerializeToString,
            resource_dot_logic_dot_admin__permission__group__pb2.AdminPermissionGroupShowAdminPermissionGroupsTotalByFiltersWithSortersPaginationOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
