# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.logic import admin_user_pb2 as resource_dot_logic_dot_admin__user__pb2


class AdminUserLogicStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShowAdminUsersTotalByFiltersWithSortersPagination = channel.unary_unary(
                '/pb.resource.logic.AdminUserLogic/ShowAdminUsersTotalByFiltersWithSortersPagination',
                request_serializer=resource_dot_logic_dot_admin__user__pb2.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_admin__user__pb2.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput.FromString,
                _registered_method=True)
        self.ShowAdminUserById = channel.unary_unary(
                '/pb.resource.logic.AdminUserLogic/ShowAdminUserById',
                request_serializer=resource_dot_logic_dot_admin__user__pb2.AdminUserShowAdminUserByIdInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_admin__user__pb2.AdminUserShowAdminUserByIdOutput.FromString,
                _registered_method=True)
        self.AddAminUser = channel.unary_unary(
                '/pb.resource.logic.AdminUserLogic/AddAminUser',
                request_serializer=resource_dot_logic_dot_admin__user__pb2.AdminUserAddAminUserInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_admin__user__pb2.AdminUserAddAminUserOutput.FromString,
                _registered_method=True)
        self.EditAdminUserById = channel.unary_unary(
                '/pb.resource.logic.AdminUserLogic/EditAdminUserById',
                request_serializer=resource_dot_logic_dot_admin__user__pb2.AdminUserEditAdminUserByIdInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_admin__user__pb2.AdminUserEditAdminUserByIdOutput.FromString,
                _registered_method=True)
        self.RemoveAdminUserById = channel.unary_unary(
                '/pb.resource.logic.AdminUserLogic/RemoveAdminUserById',
                request_serializer=resource_dot_logic_dot_admin__user__pb2.AdminUserRemoveAdminUserByIdInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_admin__user__pb2.AdminUserRemoveAdminUserByIdOutput.FromString,
                _registered_method=True)


class AdminUserLogicServicer:
    """Missing associated documentation comment in .proto file."""

    def ShowAdminUsersTotalByFiltersWithSortersPagination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowAdminUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAminUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditAdminUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAdminUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminUserLogicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShowAdminUsersTotalByFiltersWithSortersPagination': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowAdminUsersTotalByFiltersWithSortersPagination,
                    request_deserializer=resource_dot_logic_dot_admin__user__pb2.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput.FromString,
                    response_serializer=resource_dot_logic_dot_admin__user__pb2.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput.SerializeToString,
            ),
            'ShowAdminUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowAdminUserById,
                    request_deserializer=resource_dot_logic_dot_admin__user__pb2.AdminUserShowAdminUserByIdInput.FromString,
                    response_serializer=resource_dot_logic_dot_admin__user__pb2.AdminUserShowAdminUserByIdOutput.SerializeToString,
            ),
            'AddAminUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAminUser,
                    request_deserializer=resource_dot_logic_dot_admin__user__pb2.AdminUserAddAminUserInput.FromString,
                    response_serializer=resource_dot_logic_dot_admin__user__pb2.AdminUserAddAminUserOutput.SerializeToString,
            ),
            'EditAdminUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.EditAdminUserById,
                    request_deserializer=resource_dot_logic_dot_admin__user__pb2.AdminUserEditAdminUserByIdInput.FromString,
                    response_serializer=resource_dot_logic_dot_admin__user__pb2.AdminUserEditAdminUserByIdOutput.SerializeToString,
            ),
            'RemoveAdminUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAdminUserById,
                    request_deserializer=resource_dot_logic_dot_admin__user__pb2.AdminUserRemoveAdminUserByIdInput.FromString,
                    response_serializer=resource_dot_logic_dot_admin__user__pb2.AdminUserRemoveAdminUserByIdOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.logic.AdminUserLogic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.logic.AdminUserLogic', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminUserLogic:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShowAdminUsersTotalByFiltersWithSortersPagination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AdminUserLogic/ShowAdminUsersTotalByFiltersWithSortersPagination',
            resource_dot_logic_dot_admin__user__pb2.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput.SerializeToString,
            resource_dot_logic_dot_admin__user__pb2.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowAdminUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AdminUserLogic/ShowAdminUserById',
            resource_dot_logic_dot_admin__user__pb2.AdminUserShowAdminUserByIdInput.SerializeToString,
            resource_dot_logic_dot_admin__user__pb2.AdminUserShowAdminUserByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddAminUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AdminUserLogic/AddAminUser',
            resource_dot_logic_dot_admin__user__pb2.AdminUserAddAminUserInput.SerializeToString,
            resource_dot_logic_dot_admin__user__pb2.AdminUserAddAminUserOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditAdminUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AdminUserLogic/EditAdminUserById',
            resource_dot_logic_dot_admin__user__pb2.AdminUserEditAdminUserByIdInput.SerializeToString,
            resource_dot_logic_dot_admin__user__pb2.AdminUserEditAdminUserByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAdminUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AdminUserLogic/RemoveAdminUserById',
            resource_dot_logic_dot_admin__user__pb2.AdminUserRemoveAdminUserByIdInput.SerializeToString,
            resource_dot_logic_dot_admin__user__pb2.AdminUserRemoveAdminUserByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
