# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/logic/admin_role.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'resource/logic/admin_role.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fresource/logic/admin_role.proto\x12\x11pb.resource.logic\x1a\x0c\x63ommon.proto\"O\n\x1a\x41\x64minRoleAddAdminRoleInput\x12\x31\n\x08variable\x18\x01 \x01(\x0b\x32\x15.pb.AdminRoleVariableR\x08variable\"\x1d\n\x1b\x41\x64minRoleAddAdminRoleOutput2\x7f\n\x0e\x41\x64minRoleLogic\x12m\n\x0c\x41\x64\x64\x41\x64minRole\x12-.pb.resource.logic.AdminRoleAddAdminRoleInput\x1a..pb.resource.logic.AdminRoleAddAdminRoleOutputB\xca\x01\n\x15\x63om.pb.resource.logicB\x0e\x41\x64minRoleProtoP\x01Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/logic\xa2\x02\x03PRL\xaa\x02\x11Pb.Resource.Logic\xca\x02\x11Pb\\Resource\\Logic\xe2\x02\x1dPb\\Resource\\Logic\\GPBMetadata\xea\x02\x13Pb::Resource::Logicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.logic.admin_role_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.pb.resource.logicB\016AdminRoleProtoP\001Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/logic\242\002\003PRL\252\002\021Pb.Resource.Logic\312\002\021Pb\\Resource\\Logic\342\002\035Pb\\Resource\\Logic\\GPBMetadata\352\002\023Pb::Resource::Logic'
  _globals['_ADMINROLEADDADMINROLEINPUT']._serialized_start=68
  _globals['_ADMINROLEADDADMINROLEINPUT']._serialized_end=147
  _globals['_ADMINROLEADDADMINROLEOUTPUT']._serialized_start=149
  _globals['_ADMINROLEADDADMINROLEOUTPUT']._serialized_end=178
  _globals['_ADMINROLELOGIC']._serialized_start=180
  _globals['_ADMINROLELOGIC']._serialized_end=307
# @@protoc_insertion_point(module_scope)
