# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/logic/app_user.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'resource/logic/app_user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dresource/logic/app_user.proto\x12\x11pb.resource.logic\x1a\x0c\x63ommon.proto\"I\n\x16\x41ppUserAddAppUserInput\x12/\n\x08variable\x18\x01 \x01(\x0b\x32\x13.pb.AppUserVariableR\x08variable\"A\n\x17\x41ppUserAddAppUserOutput\x12&\n\x08\x61pp_user\x18\x01 \x01(\x0b\x32\x0b.pb.AppUserR\x07\x61ppUser2s\n\x0c\x41ppUserModel\x12\x63\n\nAddAppUser\x12).pb.resource.logic.AppUserAddAppUserInput\x1a*.pb.resource.logic.AppUserAddAppUserOutputB\xc8\x01\n\x15\x63om.pb.resource.logicB\x0c\x41ppUserProtoP\x01Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/logic\xa2\x02\x03PRL\xaa\x02\x11Pb.Resource.Logic\xca\x02\x11Pb\\Resource\\Logic\xe2\x02\x1dPb\\Resource\\Logic\\GPBMetadata\xea\x02\x13Pb::Resource::Logicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.logic.app_user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.pb.resource.logicB\014AppUserProtoP\001Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/logic\242\002\003PRL\252\002\021Pb.Resource.Logic\312\002\021Pb\\Resource\\Logic\342\002\035Pb\\Resource\\Logic\\GPBMetadata\352\002\023Pb::Resource::Logic'
  _globals['_APPUSERADDAPPUSERINPUT']._serialized_start=66
  _globals['_APPUSERADDAPPUSERINPUT']._serialized_end=139
  _globals['_APPUSERADDAPPUSEROUTPUT']._serialized_start=141
  _globals['_APPUSERADDAPPUSEROUTPUT']._serialized_end=206
  _globals['_APPUSERMODEL']._serialized_start=208
  _globals['_APPUSERMODEL']._serialized_end=323
# @@protoc_insertion_point(module_scope)
