# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.logic import app_user_pb2 as resource_dot_logic_dot_app__user__pb2


class AppUserModelStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddAppUser = channel.unary_unary(
                '/pb.resource.logic.AppUserModel/AddAppUser',
                request_serializer=resource_dot_logic_dot_app__user__pb2.AppUserAddAppUserInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_app__user__pb2.AppUserAddAppUserOutput.FromString,
                _registered_method=True)


class AppUserModelServicer:
    """Missing associated documentation comment in .proto file."""

    def AddAppUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppUserModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddAppUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAppUser,
                    request_deserializer=resource_dot_logic_dot_app__user__pb2.AppUserAddAppUserInput.FromString,
                    response_serializer=resource_dot_logic_dot_app__user__pb2.AppUserAddAppUserOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.logic.AppUserModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.logic.AppUserModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppUserModel:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddAppUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.AppUserModel/AddAppUser',
            resource_dot_logic_dot_app__user__pb2.AppUserAddAppUserInput.SerializeToString,
            resource_dot_logic_dot_app__user__pb2.AppUserAddAppUserOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
