# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/logic/game_type.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'resource/logic/game_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eresource/logic/game_type.proto\x12\x11pb.resource.logic\x1a\x0c\x63ommon.proto\"\x17\n\x15GameTypeShowTreeInput\"E\n\x16GameTypeShowTreeOutput\x12+\n\ngame_types\x18\x01 \x03(\x0b\x32\x0c.pb.GameTypeR\tgameTypes\"/\n\x1dGameTypeShowGameTypeByIdInput\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\"K\n\x1eGameTypeShowGameTypeByIdOutput\x12)\n\tgame_type\x18\x01 \x01(\x0b\x32\x0c.pb.GameTypeR\x08gameType\"\x1c\n\x1aGameTypeShowGameTypesInput\"J\n\x1bGameTypeShowGameTypesOutput\x12+\n\ngame_types\x18\x01 \x03(\x0b\x32\x0c.pb.GameTypeR\tgameTypes\"\xbb\x01\n=GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput\x12$\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\n.pb.FilterR\x07\x66ilters\x12$\n\x07sorters\x18\x02 \x03(\x0b\x32\n.pb.SorterR\x07sorters\x12.\n\npagination\x18\x03 \x01(\x0b\x32\x0e.pb.PaginationR\npagination\"\x83\x01\n>GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput\x12+\n\ngame_types\x18\x01 \x03(\x0b\x32\x0c.pb.GameTypeR\tgameTypes\x12\x14\n\x05total\x18\x02 \x01(\x04R\x05total2\xb3\x04\n\rGameTypeLogic\x12_\n\x08ShowTree\x12(.pb.resource.logic.GameTypeShowTreeInput\x1a).pb.resource.logic.GameTypeShowTreeOutput\x12w\n\x10ShowGameTypeById\x12\x30.pb.resource.logic.GameTypeShowGameTypeByIdInput\x1a\x31.pb.resource.logic.GameTypeShowGameTypeByIdOutput\x12n\n\rShowGameTypes\x12-.pb.resource.logic.GameTypeShowGameTypesInput\x1a..pb.resource.logic.GameTypeShowGameTypesOutput\x12\xd7\x01\n0ShowGameTypesTotalByFiltersWithSortersPagination\x12P.pb.resource.logic.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput\x1aQ.pb.resource.logic.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutputB\xc9\x01\n\x15\x63om.pb.resource.logicB\rGameTypeProtoP\x01Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/logic\xa2\x02\x03PRL\xaa\x02\x11Pb.Resource.Logic\xca\x02\x11Pb\\Resource\\Logic\xe2\x02\x1dPb\\Resource\\Logic\\GPBMetadata\xea\x02\x13Pb::Resource::Logicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.logic.game_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.pb.resource.logicB\rGameTypeProtoP\001Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/logic\242\002\003PRL\252\002\021Pb.Resource.Logic\312\002\021Pb\\Resource\\Logic\342\002\035Pb\\Resource\\Logic\\GPBMetadata\352\002\023Pb::Resource::Logic'
  _globals['_GAMETYPESHOWTREEINPUT']._serialized_start=67
  _globals['_GAMETYPESHOWTREEINPUT']._serialized_end=90
  _globals['_GAMETYPESHOWTREEOUTPUT']._serialized_start=92
  _globals['_GAMETYPESHOWTREEOUTPUT']._serialized_end=161
  _globals['_GAMETYPESHOWGAMETYPEBYIDINPUT']._serialized_start=163
  _globals['_GAMETYPESHOWGAMETYPEBYIDINPUT']._serialized_end=210
  _globals['_GAMETYPESHOWGAMETYPEBYIDOUTPUT']._serialized_start=212
  _globals['_GAMETYPESHOWGAMETYPEBYIDOUTPUT']._serialized_end=287
  _globals['_GAMETYPESHOWGAMETYPESINPUT']._serialized_start=289
  _globals['_GAMETYPESHOWGAMETYPESINPUT']._serialized_end=317
  _globals['_GAMETYPESHOWGAMETYPESOUTPUT']._serialized_start=319
  _globals['_GAMETYPESHOWGAMETYPESOUTPUT']._serialized_end=393
  _globals['_GAMETYPESHOWGAMETYPESTOTALBYFILTERSWITHSORTERSPAGINATIONINPUT']._serialized_start=396
  _globals['_GAMETYPESHOWGAMETYPESTOTALBYFILTERSWITHSORTERSPAGINATIONINPUT']._serialized_end=583
  _globals['_GAMETYPESHOWGAMETYPESTOTALBYFILTERSWITHSORTERSPAGINATIONOUTPUT']._serialized_start=586
  _globals['_GAMETYPESHOWGAMETYPESTOTALBYFILTERSWITHSORTERSPAGINATIONOUTPUT']._serialized_end=717
  _globals['_GAMETYPELOGIC']._serialized_start=720
  _globals['_GAMETYPELOGIC']._serialized_end=1283
# @@protoc_insertion_point(module_scope)
