# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.logic import game_type_pb2 as resource_dot_logic_dot_game__type__pb2


class GameTypeLogicStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShowTree = channel.unary_unary(
                '/pb.resource.logic.GameTypeLogic/ShowTree',
                request_serializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowTreeInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowTreeOutput.FromString,
                _registered_method=True)
        self.ShowGameTypeById = channel.unary_unary(
                '/pb.resource.logic.GameTypeLogic/ShowGameTypeById',
                request_serializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypeByIdInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypeByIdOutput.FromString,
                _registered_method=True)
        self.ShowGameTypes = channel.unary_unary(
                '/pb.resource.logic.GameTypeLogic/ShowGameTypes',
                request_serializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypesInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypesOutput.FromString,
                _registered_method=True)
        self.ShowGameTypesTotalByFiltersWithSortersPagination = channel.unary_unary(
                '/pb.resource.logic.GameTypeLogic/ShowGameTypesTotalByFiltersWithSortersPagination',
                request_serializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput.FromString,
                _registered_method=True)


class GameTypeLogicServicer:
    """Missing associated documentation comment in .proto file."""

    def ShowTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowGameTypeById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowGameTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowGameTypesTotalByFiltersWithSortersPagination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameTypeLogicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShowTree': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowTree,
                    request_deserializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowTreeInput.FromString,
                    response_serializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowTreeOutput.SerializeToString,
            ),
            'ShowGameTypeById': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowGameTypeById,
                    request_deserializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypeByIdInput.FromString,
                    response_serializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypeByIdOutput.SerializeToString,
            ),
            'ShowGameTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowGameTypes,
                    request_deserializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypesInput.FromString,
                    response_serializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypesOutput.SerializeToString,
            ),
            'ShowGameTypesTotalByFiltersWithSortersPagination': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowGameTypesTotalByFiltersWithSortersPagination,
                    request_deserializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput.FromString,
                    response_serializer=resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.logic.GameTypeLogic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.logic.GameTypeLogic', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameTypeLogic:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShowTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.GameTypeLogic/ShowTree',
            resource_dot_logic_dot_game__type__pb2.GameTypeShowTreeInput.SerializeToString,
            resource_dot_logic_dot_game__type__pb2.GameTypeShowTreeOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowGameTypeById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.GameTypeLogic/ShowGameTypeById',
            resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypeByIdInput.SerializeToString,
            resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypeByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowGameTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.GameTypeLogic/ShowGameTypes',
            resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypesInput.SerializeToString,
            resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypesOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowGameTypesTotalByFiltersWithSortersPagination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.GameTypeLogic/ShowGameTypesTotalByFiltersWithSortersPagination',
            resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput.SerializeToString,
            resource_dot_logic_dot_game__type__pb2.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
