# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/logic/game.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'resource/logic/game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19resource/logic/game.proto\x12\x11pb.resource.logic\x1a\x0c\x63ommon.proto\"\xb3\x01\n5GameShowGamesTotalByFiltersWithSortersPaginationInput\x12$\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\n.pb.FilterR\x07\x66ilters\x12$\n\x07sorters\x18\x02 \x03(\x0b\x32\n.pb.SorterR\x07sorters\x12.\n\npagination\x18\x03 \x01(\x0b\x32\x0e.pb.PaginationR\npagination\"n\n6GameShowGamesTotalByFiltersWithSortersPaginationOutput\x12\x1e\n\x05games\x18\x01 \x03(\x0b\x32\x08.pb.GameR\x05games\x12\x14\n\x05total\x18\x02 \x01(\x04R\x05total2\xd1\x01\n\tGameLogic\x12\xc3\x01\n,ShowGamesTotalByFiltersWithSortersPagination\x12H.pb.resource.logic.GameShowGamesTotalByFiltersWithSortersPaginationInput\x1aI.pb.resource.logic.GameShowGamesTotalByFiltersWithSortersPaginationOutputB\xc5\x01\n\x15\x63om.pb.resource.logicB\tGameProtoP\x01Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/logic\xa2\x02\x03PRL\xaa\x02\x11Pb.Resource.Logic\xca\x02\x11Pb\\Resource\\Logic\xe2\x02\x1dPb\\Resource\\Logic\\GPBMetadata\xea\x02\x13Pb::Resource::Logicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.logic.game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.pb.resource.logicB\tGameProtoP\001Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/logic\242\002\003PRL\252\002\021Pb.Resource.Logic\312\002\021Pb\\Resource\\Logic\342\002\035Pb\\Resource\\Logic\\GPBMetadata\352\002\023Pb::Resource::Logic'
  _globals['_GAMESHOWGAMESTOTALBYFILTERSWITHSORTERSPAGINATIONINPUT']._serialized_start=63
  _globals['_GAMESHOWGAMESTOTALBYFILTERSWITHSORTERSPAGINATIONINPUT']._serialized_end=242
  _globals['_GAMESHOWGAMESTOTALBYFILTERSWITHSORTERSPAGINATIONOUTPUT']._serialized_start=244
  _globals['_GAMESHOWGAMESTOTALBYFILTERSWITHSORTERSPAGINATIONOUTPUT']._serialized_end=354
  _globals['_GAMELOGIC']._serialized_start=357
  _globals['_GAMELOGIC']._serialized_end=566
# @@protoc_insertion_point(module_scope)
