# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.logic import game_pb2 as resource_dot_logic_dot_game__pb2


class GameLogicStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShowGamesTotalByFiltersWithSortersPagination = channel.unary_unary(
                '/pb.resource.logic.GameLogic/ShowGamesTotalByFiltersWithSortersPagination',
                request_serializer=resource_dot_logic_dot_game__pb2.GameShowGamesTotalByFiltersWithSortersPaginationInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_game__pb2.GameShowGamesTotalByFiltersWithSortersPaginationOutput.FromString,
                _registered_method=True)


class GameLogicServicer:
    """Missing associated documentation comment in .proto file."""

    def ShowGamesTotalByFiltersWithSortersPagination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameLogicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShowGamesTotalByFiltersWithSortersPagination': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowGamesTotalByFiltersWithSortersPagination,
                    request_deserializer=resource_dot_logic_dot_game__pb2.GameShowGamesTotalByFiltersWithSortersPaginationInput.FromString,
                    response_serializer=resource_dot_logic_dot_game__pb2.GameShowGamesTotalByFiltersWithSortersPaginationOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.logic.GameLogic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.logic.GameLogic', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameLogic:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShowGamesTotalByFiltersWithSortersPagination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.GameLogic/ShowGamesTotalByFiltersWithSortersPagination',
            resource_dot_logic_dot_game__pb2.GameShowGamesTotalByFiltersWithSortersPaginationInput.SerializeToString,
            resource_dot_logic_dot_game__pb2.GameShowGamesTotalByFiltersWithSortersPaginationOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
