# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.logic import table_pb2 as resource_dot_logic_dot_table__pb2


class TableLogicStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShowTableById = channel.unary_unary(
                '/pb.resource.logic.TableLogic/ShowTableById',
                request_serializer=resource_dot_logic_dot_table__pb2.TableShowTableByIdInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_table__pb2.TableShowTableByIdOutput.FromString,
                _registered_method=True)
        self.ShowTablesTotalByFiltersWithSortersPagination = channel.unary_unary(
                '/pb.resource.logic.TableLogic/ShowTablesTotalByFiltersWithSortersPagination',
                request_serializer=resource_dot_logic_dot_table__pb2.TableShowTablesTotalByFiltersWithSortersPaginationInput.SerializeToString,
                response_deserializer=resource_dot_logic_dot_table__pb2.TableShowTablesTotalByFiltersWithSortersPaginationOutput.FromString,
                _registered_method=True)


class TableLogicServicer:
    """Missing associated documentation comment in .proto file."""

    def ShowTableById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowTablesTotalByFiltersWithSortersPagination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TableLogicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShowTableById': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowTableById,
                    request_deserializer=resource_dot_logic_dot_table__pb2.TableShowTableByIdInput.FromString,
                    response_serializer=resource_dot_logic_dot_table__pb2.TableShowTableByIdOutput.SerializeToString,
            ),
            'ShowTablesTotalByFiltersWithSortersPagination': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowTablesTotalByFiltersWithSortersPagination,
                    request_deserializer=resource_dot_logic_dot_table__pb2.TableShowTablesTotalByFiltersWithSortersPaginationInput.FromString,
                    response_serializer=resource_dot_logic_dot_table__pb2.TableShowTablesTotalByFiltersWithSortersPaginationOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.logic.TableLogic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.logic.TableLogic', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TableLogic:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShowTableById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.TableLogic/ShowTableById',
            resource_dot_logic_dot_table__pb2.TableShowTableByIdInput.SerializeToString,
            resource_dot_logic_dot_table__pb2.TableShowTableByIdOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowTablesTotalByFiltersWithSortersPagination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.logic.TableLogic/ShowTablesTotalByFiltersWithSortersPagination',
            resource_dot_logic_dot_table__pb2.TableShowTablesTotalByFiltersWithSortersPaginationInput.SerializeToString,
            resource_dot_logic_dot_table__pb2.TableShowTablesTotalByFiltersWithSortersPaginationOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
