# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.source.announcement import lottery_pb2 as source_dot_announcement_dot_lottery__pb2


class LotteryControllerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Watch = channel.unary_stream(
                '/pb.source.announcement.LotteryController/Watch',
                request_serializer=source_dot_announcement_dot_lottery__pb2.LotteryWatchRequest.SerializeToString,
                response_deserializer=source_dot_announcement_dot_lottery__pb2.LotteryWatchResponse.FromString,
                _registered_method=True)


class LotteryControllerServicer:
    """Missing associated documentation comment in .proto file."""

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LotteryControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=source_dot_announcement_dot_lottery__pb2.LotteryWatchRequest.FromString,
                    response_serializer=source_dot_announcement_dot_lottery__pb2.LotteryWatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.source.announcement.LotteryController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.source.announcement.LotteryController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LotteryController:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pb.source.announcement.LotteryController/Watch',
            source_dot_announcement_dot_lottery__pb2.LotteryWatchRequest.SerializeToString,
            source_dot_announcement_dot_lottery__pb2.LotteryWatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
