# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recognition/ir/monitor/capture/screenshot.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'recognition/ir/monitor/capture/screenshot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/recognition/ir/monitor/capture/screenshot.proto\x12!pb.recognition.ir.monitor.capture\"\x17\n\x15ScreenshotMakeRequest\"\x18\n\x16ScreenshotMakeResponse2\x90\x01\n\x11ScreenshotService\x12{\n\x04Make\x12\x38.pb.recognition.ir.monitor.capture.ScreenshotMakeRequest\x1a\x39.pb.recognition.ir.monitor.capture.ScreenshotMakeResponseB\xaf\x02\n%com.pb.recognition.ir.monitor.captureB\x0fScreenshotProtoP\x01ZKgithub.com/wegdevio/pk-studio-reader/pkg/api/recognition/ir/monitor/capture\xa2\x02\x05PRIMC\xaa\x02!Pb.Recognition.Ir.Monitor.Capture\xca\x02!Pb\\Recognition\\Ir\\Monitor\\Capture\xe2\x02-Pb\\Recognition\\Ir\\Monitor\\Capture\\GPBMetadata\xea\x02%Pb::Recognition::Ir::Monitor::Captureb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recognition.ir.monitor.capture.screenshot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.pb.recognition.ir.monitor.captureB\017ScreenshotProtoP\001ZKgithub.com/wegdevio/pk-studio-reader/pkg/api/recognition/ir/monitor/capture\242\002\005PRIMC\252\002!Pb.Recognition.Ir.Monitor.Capture\312\002!Pb\\Recognition\\Ir\\Monitor\\Capture\342\002-Pb\\Recognition\\Ir\\Monitor\\Capture\\GPBMetadata\352\002%Pb::Recognition::Ir::Monitor::Capture'
  _globals['_SCREENSHOTMAKEREQUEST']._serialized_start=86
  _globals['_SCREENSHOTMAKEREQUEST']._serialized_end=109
  _globals['_SCREENSHOTMAKERESPONSE']._serialized_start=111
  _globals['_SCREENSHOTMAKERESPONSE']._serialized_end=135
  _globals['_SCREENSHOTSERVICE']._serialized_start=138
  _globals['_SCREENSHOTSERVICE']._serialized_end=282
# @@protoc_insertion_point(module_scope)
