# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.recognition.ir.monitor.capture import screenshot_pb2 as recognition_dot_ir_dot_monitor_dot_capture_dot_screenshot__pb2


class ScreenshotServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Make = channel.unary_unary(
                '/pb.recognition.ir.monitor.capture.ScreenshotService/Make',
                request_serializer=recognition_dot_ir_dot_monitor_dot_capture_dot_screenshot__pb2.ScreenshotMakeRequest.SerializeToString,
                response_deserializer=recognition_dot_ir_dot_monitor_dot_capture_dot_screenshot__pb2.ScreenshotMakeResponse.FromString,
                _registered_method=True)


class ScreenshotServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Make(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScreenshotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Make': grpc.unary_unary_rpc_method_handler(
                    servicer.Make,
                    request_deserializer=recognition_dot_ir_dot_monitor_dot_capture_dot_screenshot__pb2.ScreenshotMakeRequest.FromString,
                    response_serializer=recognition_dot_ir_dot_monitor_dot_capture_dot_screenshot__pb2.ScreenshotMakeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.recognition.ir.monitor.capture.ScreenshotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.recognition.ir.monitor.capture.ScreenshotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScreenshotService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Make(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.recognition.ir.monitor.capture.ScreenshotService/Make',
            recognition_dot_ir_dot_monitor_dot_capture_dot_screenshot__pb2.ScreenshotMakeRequest.SerializeToString,
            recognition_dot_ir_dot_monitor_dot_capture_dot_screenshot__pb2.ScreenshotMakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
