# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.resource.event import admin_user_pb2 as resource_dot_event_dot_admin__user__pb2


class AdminUserEventStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddOne = channel.unary_unary(
                '/pb.resource.event.AdminUserEvent/AddOne',
                request_serializer=resource_dot_event_dot_admin__user__pb2.AdminUserEventAddOneInput.SerializeToString,
                response_deserializer=resource_dot_event_dot_admin__user__pb2.AdminUserEventAddOneOutput.FromString,
                _registered_method=True)


class AdminUserEventServicer:
    """Missing associated documentation comment in .proto file."""

    def AddOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminUserEventServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddOne': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOne,
                    request_deserializer=resource_dot_event_dot_admin__user__pb2.AdminUserEventAddOneInput.FromString,
                    response_serializer=resource_dot_event_dot_admin__user__pb2.AdminUserEventAddOneOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.resource.event.AdminUserEvent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.resource.event.AdminUserEvent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminUserEvent:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.resource.event.AdminUserEvent/AddOne',
            resource_dot_event_dot_admin__user__pb2.AdminUserEventAddOneInput.SerializeToString,
            resource_dot_event_dot_admin__user__pb2.AdminUserEventAddOneOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
