# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/event/admin_user.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'resource/event/admin_user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fresource/event/admin_user.proto\x12\x11pb.resource.event\x1a\x0c\x63ommon.proto\"L\n\x19\x41\x64minUserEventAddOneInput\x12/\n\x08variable\x18\x01 \x01(\x0b\x32\x13.pb.AppUserVariableR\x08variable\"\x1c\n\x1a\x41\x64minUserEventAddOneOutput2w\n\x0e\x41\x64minUserEvent\x12\x65\n\x06\x41\x64\x64One\x12,.pb.resource.event.AdminUserEventAddOneInput\x1a-.pb.resource.event.AdminUserEventAddOneOutputB\xca\x01\n\x15\x63om.pb.resource.eventB\x0e\x41\x64minUserProtoP\x01Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/event\xa2\x02\x03PRE\xaa\x02\x11Pb.Resource.Event\xca\x02\x11Pb\\Resource\\Event\xe2\x02\x1dPb\\Resource\\Event\\GPBMetadata\xea\x02\x13Pb::Resource::Eventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.event.admin_user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.pb.resource.eventB\016AdminUserProtoP\001Z;github.com/wegdevio/pk-studio-reader/pkg/api/resource/event\242\002\003PRE\252\002\021Pb.Resource.Event\312\002\021Pb\\Resource\\Event\342\002\035Pb\\Resource\\Event\\GPBMetadata\352\002\023Pb::Resource::Event'
  _globals['_ADMINUSEREVENTADDONEINPUT']._serialized_start=68
  _globals['_ADMINUSEREVENTADDONEINPUT']._serialized_end=144
  _globals['_ADMINUSEREVENTADDONEOUTPUT']._serialized_start=146
  _globals['_ADMINUSEREVENTADDONEOUTPUT']._serialized_end=174
  _globals['_ADMINUSEREVENT']._serialized_start=176
  _globals['_ADMINUSEREVENT']._serialized_end=295
# @@protoc_insertion_point(module_scope)
