# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.ir.table.inference.game import baccarat_pb2 as ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2


class BaccaratServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizePoker = channel.unary_unary(
                '/pb.ir.table.inference.game.BaccaratService/RecognizePoker',
                request_serializer=ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizePokerRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizePokerResponse.FromString,
                _registered_method=True)
        self.RecognizeObject = channel.unary_stream(
                '/pb.ir.table.inference.game.BaccaratService/RecognizeObject',
                request_serializer=ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizeSceneRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizeSceneResponse.FromString,
                _registered_method=True)
        self.RecognizeAll = channel.unary_unary(
                '/pb.ir.table.inference.game.BaccaratService/RecognizeAll',
                request_serializer=ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizeAllRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizeAllResponse.FromString,
                _registered_method=True)


class BaccaratServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RecognizePoker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BaccaratServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizePoker': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizePoker,
                    request_deserializer=ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizePokerRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizePokerResponse.SerializeToString,
            ),
            'RecognizeObject': grpc.unary_stream_rpc_method_handler(
                    servicer.RecognizeObject,
                    request_deserializer=ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizeSceneRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizeSceneResponse.SerializeToString,
            ),
            'RecognizeAll': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeAll,
                    request_deserializer=ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizeAllRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizeAllResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ir.table.inference.game.BaccaratService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.ir.table.inference.game.BaccaratService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BaccaratService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizePoker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.game.BaccaratService/RecognizePoker',
            ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizePokerRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizePokerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pb.ir.table.inference.game.BaccaratService/RecognizeObject',
            ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizeSceneRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizeSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.game.BaccaratService/RecognizeAll',
            ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizeAllRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_game_dot_baccarat__pb2.BaccaratRecognizeAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
