# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ir/table/inference/game/baccarat.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'ir/table/inference/game/baccarat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb.ir import ir_pb2 as ir_dot_ir__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ir/table/inference/game/baccarat.proto\x12\x1apb.ir.table.inference.game\x1a\x0bir/ir.proto\"\x1f\n\x1d\x42\x61\x63\x63\x61ratRecognizePokerRequest\"D\n\x1e\x42\x61\x63\x63\x61ratRecognizePokerResponse\x12\"\n\x05items\x18\x01 \x03(\x0b\x32\x0c.pb.ir.PokerR\x05items\"\x1f\n\x1d\x42\x61\x63\x63\x61ratRecognizeSceneRequest\"\x1d\n\x1b\x42\x61\x63\x63\x61ratRecognizeAllRequest\"I\n\x1e\x42\x61\x63\x63\x61ratRecognizeSceneResponse\x12\'\n\x07objects\x18\x01 \x03(\x0b\x32\r.pb.ir.ObjectR\x07objects\"k\n\x1c\x42\x61\x63\x63\x61ratRecognizeAllResponse\x12\'\n\x07objects\x18\x01 \x03(\x0b\x32\r.pb.ir.ObjectR\x07objects\x12\"\n\x05items\x18\x02 \x03(\x0b\x32\x0c.pb.ir.PokerR\x05items2\xac\x03\n\x0f\x42\x61\x63\x63\x61ratService\x12\x87\x01\n\x0eRecognizePoker\x12\x39.pb.ir.table.inference.game.BaccaratRecognizePokerRequest\x1a:.pb.ir.table.inference.game.BaccaratRecognizePokerResponse\x12\x8a\x01\n\x0fRecognizeObject\x12\x39.pb.ir.table.inference.game.BaccaratRecognizeSceneRequest\x1a:.pb.ir.table.inference.game.BaccaratRecognizeSceneResponse0\x01\x12\x81\x01\n\x0cRecognizeAll\x12\x37.pb.ir.table.inference.game.BaccaratRecognizeAllRequest\x1a\x38.pb.ir.table.inference.game.BaccaratRecognizeAllResponseB\x83\x02\n\x1e\x63om.pb.ir.table.inference.gameB\rBaccaratProtoP\x01ZDgithub.com/wegdevio/pk-studio-reader/pkg/api/ir/table/inference/game\xa2\x02\x05PITIG\xaa\x02\x1aPb.Ir.Table.Inference.Game\xca\x02\x1aPb\\Ir\\Table\\Inference\\Game\xe2\x02&Pb\\Ir\\Table\\Inference\\Game\\GPBMetadata\xea\x02\x1ePb::Ir::Table::Inference::Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ir.table.inference.game.baccarat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.pb.ir.table.inference.gameB\rBaccaratProtoP\001ZDgithub.com/wegdevio/pk-studio-reader/pkg/api/ir/table/inference/game\242\002\005PITIG\252\002\032Pb.Ir.Table.Inference.Game\312\002\032Pb\\Ir\\Table\\Inference\\Game\342\002&Pb\\Ir\\Table\\Inference\\Game\\GPBMetadata\352\002\036Pb::Ir::Table::Inference::Game'
  _globals['_BACCARATRECOGNIZEPOKERREQUEST']._serialized_start=83
  _globals['_BACCARATRECOGNIZEPOKERREQUEST']._serialized_end=114
  _globals['_BACCARATRECOGNIZEPOKERRESPONSE']._serialized_start=116
  _globals['_BACCARATRECOGNIZEPOKERRESPONSE']._serialized_end=184
  _globals['_BACCARATRECOGNIZESCENEREQUEST']._serialized_start=186
  _globals['_BACCARATRECOGNIZESCENEREQUEST']._serialized_end=217
  _globals['_BACCARATRECOGNIZEALLREQUEST']._serialized_start=219
  _globals['_BACCARATRECOGNIZEALLREQUEST']._serialized_end=248
  _globals['_BACCARATRECOGNIZESCENERESPONSE']._serialized_start=250
  _globals['_BACCARATRECOGNIZESCENERESPONSE']._serialized_end=323
  _globals['_BACCARATRECOGNIZEALLRESPONSE']._serialized_start=325
  _globals['_BACCARATRECOGNIZEALLRESPONSE']._serialized_end=432
  _globals['_BACCARATSERVICE']._serialized_start=435
  _globals['_BACCARATSERVICE']._serialized_end=863
# @@protoc_insertion_point(module_scope)
