# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ir/table/inference/game/sicbo.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'ir/table/inference/game/sicbo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb.ir import ir_pb2 as ir_dot_ir__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ir/table/inference/game/sicbo.proto\x12\x1apb.ir.table.inference.game\x1a\x0bir/ir.proto\"\x1a\n\x18SicboRecognizeDieRequest\"=\n\x19SicboRecognizeDieResponse\x12 \n\x05items\x18\x01 \x03(\x0b\x32\n.pb.ir.DieR\x05items\"\x1c\n\x1aSicboRecognizeSceneRequest\"\x1a\n\x18SicboRecognizeAllRequest\"F\n\x1bSicboRecognizeSceneResponse\x12\'\n\x07objects\x18\x01 \x03(\x0b\x32\r.pb.ir.ObjectR\x07objects\"f\n\x19SicboRecognizeAllResponse\x12\'\n\x07objects\x18\x01 \x03(\x0b\x32\r.pb.ir.ObjectR\x07objects\x12 \n\x05items\x18\x02 \x03(\x0b\x32\n.pb.ir.DieR\x05items2\x8f\x03\n\x0cSicboService\x12{\n\x0cRecognizeDie\x12\x34.pb.ir.table.inference.game.SicboRecognizeDieRequest\x1a\x35.pb.ir.table.inference.game.SicboRecognizeDieResponse\x12\x84\x01\n\x0fRecognizeObject\x12\x36.pb.ir.table.inference.game.SicboRecognizeSceneRequest\x1a\x37.pb.ir.table.inference.game.SicboRecognizeSceneResponse0\x01\x12{\n\x0cRecognizeAll\x12\x34.pb.ir.table.inference.game.SicboRecognizeAllRequest\x1a\x35.pb.ir.table.inference.game.SicboRecognizeAllResponseB\x80\x02\n\x1e\x63om.pb.ir.table.inference.gameB\nSicboProtoP\x01ZDgithub.com/wegdevio/pk-studio-reader/pkg/api/ir/table/inference/game\xa2\x02\x05PITIG\xaa\x02\x1aPb.Ir.Table.Inference.Game\xca\x02\x1aPb\\Ir\\Table\\Inference\\Game\xe2\x02&Pb\\Ir\\Table\\Inference\\Game\\GPBMetadata\xea\x02\x1ePb::Ir::Table::Inference::Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ir.table.inference.game.sicbo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.pb.ir.table.inference.gameB\nSicboProtoP\001ZDgithub.com/wegdevio/pk-studio-reader/pkg/api/ir/table/inference/game\242\002\005PITIG\252\002\032Pb.Ir.Table.Inference.Game\312\002\032Pb\\Ir\\Table\\Inference\\Game\342\002&Pb\\Ir\\Table\\Inference\\Game\\GPBMetadata\352\002\036Pb::Ir::Table::Inference::Game'
  _globals['_SICBORECOGNIZEDIEREQUEST']._serialized_start=80
  _globals['_SICBORECOGNIZEDIEREQUEST']._serialized_end=106
  _globals['_SICBORECOGNIZEDIERESPONSE']._serialized_start=108
  _globals['_SICBORECOGNIZEDIERESPONSE']._serialized_end=169
  _globals['_SICBORECOGNIZESCENEREQUEST']._serialized_start=171
  _globals['_SICBORECOGNIZESCENEREQUEST']._serialized_end=199
  _globals['_SICBORECOGNIZEALLREQUEST']._serialized_start=201
  _globals['_SICBORECOGNIZEALLREQUEST']._serialized_end=227
  _globals['_SICBORECOGNIZESCENERESPONSE']._serialized_start=229
  _globals['_SICBORECOGNIZESCENERESPONSE']._serialized_end=299
  _globals['_SICBORECOGNIZEALLRESPONSE']._serialized_start=301
  _globals['_SICBORECOGNIZEALLRESPONSE']._serialized_end=403
  _globals['_SICBOSERVICE']._serialized_start=406
  _globals['_SICBOSERVICE']._serialized_end=805
# @@protoc_insertion_point(module_scope)
