# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.ir.table.inference.game import sicbo_pb2 as ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2


class SicboServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeDie = channel.unary_unary(
                '/pb.ir.table.inference.game.SicboService/RecognizeDie',
                request_serializer=ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeDieRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeDieResponse.FromString,
                _registered_method=True)
        self.RecognizeObject = channel.unary_stream(
                '/pb.ir.table.inference.game.SicboService/RecognizeObject',
                request_serializer=ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeSceneRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeSceneResponse.FromString,
                _registered_method=True)
        self.RecognizeAll = channel.unary_unary(
                '/pb.ir.table.inference.game.SicboService/RecognizeAll',
                request_serializer=ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeAllRequest.SerializeToString,
                response_deserializer=ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeAllResponse.FromString,
                _registered_method=True)


class SicboServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RecognizeDie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SicboServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeDie': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeDie,
                    request_deserializer=ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeDieRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeDieResponse.SerializeToString,
            ),
            'RecognizeObject': grpc.unary_stream_rpc_method_handler(
                    servicer.RecognizeObject,
                    request_deserializer=ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeSceneRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeSceneResponse.SerializeToString,
            ),
            'RecognizeAll': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeAll,
                    request_deserializer=ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeAllRequest.FromString,
                    response_serializer=ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeAllResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ir.table.inference.game.SicboService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.ir.table.inference.game.SicboService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SicboService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizeDie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.game.SicboService/RecognizeDie',
            ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeDieRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeDieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pb.ir.table.inference.game.SicboService/RecognizeObject',
            ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeSceneRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.ir.table.inference.game.SicboService/RecognizeAll',
            ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeAllRequest.SerializeToString,
            ir_dot_table_dot_inference_dot_game_dot_sicbo__pb2.SicboRecognizeAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
