# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: facade/admin/authentication/authenticator.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'facade/admin/authentication/authenticator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/facade/admin/authentication/authenticator.proto\x12\x1epb.facade.admin.authentication\x1a\x0c\x63ommon.proto\"O\n\x1a\x41uthenticatorSignInRequest\x12\x31\n\x08variable\x18\x01 \x01(\x0b\x32\x15.pb.AdminUserVariableR\x08variable\"\x1d\n\x1b\x41uthenticatorSignInResponse2\x9d\x01\n\x17\x41uthenticatorController\x12\x81\x01\n\x06SignIn\x12:.pb.facade.admin.authentication.AuthenticatorSignInRequest\x1a;.pb.facade.admin.authentication.AuthenticatorSignInResponseB\x9e\x02\n\"com.pb.facade.admin.authenticationB\x12\x41uthenticatorProtoP\x01ZHgithub.com/wegdevio/pk-studio-reader/pkg/api/facade/admin/authentication\xa2\x02\x04PFAA\xaa\x02\x1ePb.Facade.Admin.Authentication\xca\x02\x1ePb\\Facade\\Admin\\Authentication\xe2\x02*Pb\\Facade\\Admin\\Authentication\\GPBMetadata\xea\x02!Pb::Facade::Admin::Authenticationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'facade.admin.authentication.authenticator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.pb.facade.admin.authenticationB\022AuthenticatorProtoP\001ZHgithub.com/wegdevio/pk-studio-reader/pkg/api/facade/admin/authentication\242\002\004PFAA\252\002\036Pb.Facade.Admin.Authentication\312\002\036Pb\\Facade\\Admin\\Authentication\342\002*Pb\\Facade\\Admin\\Authentication\\GPBMetadata\352\002!Pb::Facade::Admin::Authentication'
  _globals['_AUTHENTICATORSIGNINREQUEST']._serialized_start=97
  _globals['_AUTHENTICATORSIGNINREQUEST']._serialized_end=176
  _globals['_AUTHENTICATORSIGNINRESPONSE']._serialized_start=178
  _globals['_AUTHENTICATORSIGNINRESPONSE']._serialized_end=207
  _globals['_AUTHENTICATORCONTROLLER']._serialized_start=210
  _globals['_AUTHENTICATORCONTROLLER']._serialized_end=367
# @@protoc_insertion_point(module_scope)
