# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: facade/game/table_record.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'facade/game/table_record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66\x61\x63\x61\x64\x65/game/table_record.proto\x12\x0epb.facade.gameB\xba\x01\n\x12\x63om.pb.facade.gameB\x10TableRecordProtoP\x01Z8github.com/wegdevio/pk-studio-reader/pkg/api/facade/game\xa2\x02\x03PFG\xaa\x02\x0ePb.Facade.Game\xca\x02\x0ePb\\Facade\\Game\xe2\x02\x1aPb\\Facade\\Game\\GPBMetadata\xea\x02\x10Pb::Facade::Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'facade.game.table_record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.pb.facade.gameB\020TableRecordProtoP\001Z8github.com/wegdevio/pk-studio-reader/pkg/api/facade/game\242\002\003PFG\252\002\016Pb.Facade.Game\312\002\016Pb\\Facade\\Game\342\002\032Pb\\Facade\\Game\\GPBMetadata\352\002\020Pb::Facade::Game'
# @@protoc_insertion_point(module_scope)
