# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: facade/table/scanner.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'facade/table/scanner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x66\x61\x63\x61\x64\x65/table/scanner.proto\x12\x0fpb.facade.table\"-\n\x17ScannerReportOneRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\".\n\x18ScannerReportOneResponse\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name2u\n\x11ScannerController\x12`\n\tReportOne\x12(.pb.facade.table.ScannerReportOneRequest\x1a).pb.facade.table.ScannerReportOneResponseB\xbc\x01\n\x13\x63om.pb.facade.tableB\x0cScannerProtoP\x01Z9github.com/wegdevio/pk-studio-reader/pkg/api/facade/table\xa2\x02\x03PFT\xaa\x02\x0fPb.Facade.Table\xca\x02\x0fPb\\Facade\\Table\xe2\x02\x1bPb\\Facade\\Table\\GPBMetadata\xea\x02\x11Pb::Facade::Tableb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'facade.table.scanner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.pb.facade.tableB\014ScannerProtoP\001Z9github.com/wegdevio/pk-studio-reader/pkg/api/facade/table\242\002\003PFT\252\002\017Pb.Facade.Table\312\002\017Pb\\Facade\\Table\342\002\033Pb\\Facade\\Table\\GPBMetadata\352\002\021Pb::Facade::Table'
  _globals['_SCANNERREPORTONEREQUEST']._serialized_start=47
  _globals['_SCANNERREPORTONEREQUEST']._serialized_end=92
  _globals['_SCANNERREPORTONERESPONSE']._serialized_start=94
  _globals['_SCANNERREPORTONERESPONSE']._serialized_end=140
  _globals['_SCANNERCONTROLLER']._serialized_start=142
  _globals['_SCANNERCONTROLLER']._serialized_end=259
# @@protoc_insertion_point(module_scope)
