# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.facade.table import scanner_pb2 as facade_dot_table_dot_scanner__pb2


class ScannerControllerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportOne = channel.unary_unary(
                '/pb.facade.table.ScannerController/ReportOne',
                request_serializer=facade_dot_table_dot_scanner__pb2.ScannerReportOneRequest.SerializeToString,
                response_deserializer=facade_dot_table_dot_scanner__pb2.ScannerReportOneResponse.FromString,
                _registered_method=True)


class ScannerControllerServicer:
    """Missing associated documentation comment in .proto file."""

    def ReportOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScannerControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportOne': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportOne,
                    request_deserializer=facade_dot_table_dot_scanner__pb2.ScannerReportOneRequest.FromString,
                    response_serializer=facade_dot_table_dot_scanner__pb2.ScannerReportOneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.facade.table.ScannerController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.facade.table.ScannerController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScannerController:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.facade.table.ScannerController/ReportOne',
            facade_dot_table_dot_scanner__pb2.ScannerReportOneRequest.SerializeToString,
            facade_dot_table_dot_scanner__pb2.ScannerReportOneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
